In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('used_cars.csv')

In [13]:
df['fuel_type'] = df['fuel_type'].fillna('Battery')

In [14]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",Battery,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Battery,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Battery,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Battery,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Battery,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Battery,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Battery,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Battery,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Battery,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [15]:
df=pd.read_csv('used_cars.csv')

In [16]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [17]:
df.drop(columns=['clean_title'],inplace=True)

In [18]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [19]:
df.fillna({'fuel_type': 'Battery'}, inplace=True)

In [20]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [21]:
df.fillna({'accident': 'None reported'}, inplace=True)

In [22]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [23]:
df.isna().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
price           0
dtype: int64

In [25]:
df.sort_values(by='brand', ascending=True, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
1537,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,"$10,000"
902,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,None reported,"$26,599"
2536,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,"$15,051"
2556,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,"$20,999"
885,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,None reported,"$39,650"
...,...,...,...,...,...,...,...,...,...,...,...
718,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,"$13,900"
514,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,None reported,"$65,000"
3474,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,None reported,"$44,900"
3369,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,"$36,800"
2261,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,None reported,"$5,000"

In [26]:
df.reset_index(drop=True, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,"$10,000"
1,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,None reported,"$26,599"
2,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,"$15,051"
3,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,"$20,999"
4,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,None reported,"$39,650"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,"$13,900"
4005,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,None reported,"$65,000"
4006,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,None reported,"$44,900"
4007,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,None reported,"$36,800"
4008,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,None reported,"$5,000"

In [27]:
df.columns

Index(['brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'price'],
      dtype='object')

In [28]:
selected_columns = ['brand', 'model_year', 'milage', 'fuel_type', 'accident', 'engine']
df_selected = df[selected_columns]

In [30]:
df_selected # new_data frame containin only essential columns

,brand,model_year,milage,fuel_type,accident,engine
0,Acura,2008,"193,783 mi.",Gasoline,At least 1 accident or damage reported,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel
1,Acura,2022,"16,120 mi.",Gasoline,None reported,2.4L I4 16V GDI DOHC
2,Acura,2012,"70,000 mi.",Gasoline,At least 1 accident or damage reported,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel
3,Acura,2018,"32,260 mi.",Gasoline,None reported,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel
4,Acura,2021,"29,000 mi.",Gasoline,None reported,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
...,...,...,...,...,...,...
4004,Volvo,2013,"73,000 mi.",Gasoline,None reported,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel
4005,Volvo,2020,"44,487 mi.",Plug-In Hybrid,None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...
4006,Volvo,2021,"24,158 mi.",Plug-In Hybrid,None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...
4007,Volvo,2019,"20,623 mi.",Gasoline,None reported,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
4008,smart,2008,"61,595 mi.",Gasoline,None reported,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel

In [31]:
df_selected = pd.get_dummies(df_selected, columns=['brand', 'fuel_type'], drop_first=True)
df_selected

,model_year,milage,accident,engine,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,...,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“
0,2008,"193,783 mi.",At least 1 accident or damage reported,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2022,"16,120 mi.",None reported,2.4L I4 16V GDI DOHC,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2012,"70,000 mi.",At least 1 accident or damage reported,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2018,"32,260 mi.",None reported,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2021,"29,000 mi.",None reported,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,2013,"73,000 mi.",None reported,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4005,2020,"44,487 mi.",None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4006,2021,"24,158 mi.",None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4007,2019,"20,623 mi.",None reported,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4008,2008,"61,595 mi.",None reported,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [49]:
X = df_selected  # Features
y = df['price']  # Target variable

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
df_selected.drop(columns=['milage'],inplace=True)

In [48]:
df_selected

,model_year,accident,engine,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“
0,2008,At least 1 accident or damage reported,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2022,None reported,2.4L I4 16V GDI DOHC,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2012,At least 1 accident or damage reported,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2018,None reported,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2021,None reported,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,2013,None reported,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4005,2020,None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4006,2021,None reported,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4007,2019,None reported,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4008,2008,None reported,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [56]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_selected['accident'] = label_encoder.fit_transform(df_selected['accident'])

In [57]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_selected['engine'] = label_encoder.fit_transform(df_selected['engine'])

In [58]:
df_selected

,model_year,accident,engine,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“
0,2008,0,382,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2022,1,210,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2012,0,609,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2018,1,248,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2021,1,430,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,2013,1,308,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4005,2020,1,828,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4006,2021,1,828,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4007,2019,1,679,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4008,2008,1,1112,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [59]:
# Training the model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'None reported'