In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('used_cars.csv')

In [4]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [5]:
df.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [6]:
df.drop(columns=['clean_title'],inplace=True)

In [7]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [8]:
df['fuel_type'] = df['fuel_type'].fillna('Battery')
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [11]:
df.fillna({'accident': 'No accident'}, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [14]:
df['accident'] = df['accident'].str.strip().replace({'None Reported': 'No Accident'},inplace=True)

In [16]:
df.drop(columns=['accident'],inplace=True)

In [17]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,"$34,999"
...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,"$40,000"

In [19]:
df.sort_values(by='brand', ascending=True, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
1537,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
902,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2536,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
2556,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
885,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
718,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
514,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
3474,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
3369,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"
2261,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,"$5,000"

In [20]:
df = df.reset_index(drop=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
1,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
3,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
4,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
4004,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
4005,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
4006,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
4007,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"
4008,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,"$5,000"

In [21]:
df.drop(index=4008, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
1,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
3,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
4,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
4003,Volvo,XC90 3.2,2008,"196,000 mi.",Gasoline,235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,A/T,Black,Beige,"$6,499"
4004,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
4005,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
4006,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
4007,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"

In [22]:
df.isna().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
price           0
dtype: int64

In [49]:
selected_columns = ['brand', 'model_year', 'milage', 'fuel_type', 'engine','price']
final_df = df[selected_columns]

In [50]:
final_df

,brand,model_year,milage,fuel_type,engine,price
0,Acura,2008,310.60262,Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,"$10,000"
1,Acura,2022,25.74944,Gasoline,2.4L I4 16V GDI DOHC,"$26,599"
2,Acura,2012,112.65380,Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,"$15,051"
3,Acura,2018,51.49888,Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,"$20,999"
4,Acura,2021,46.67086,Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$39,650"
...,...,...,...,...,...,...
4003,Volvo,2008,315.43064,Gasoline,235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$6,499"
4004,Volvo,2013,117.48182,Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,"$13,900"
4005,Volvo,2020,70.81096,Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$65,000"
4006,Volvo,2021,38.62416,Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$44,900"
4007,Volvo,2019,32.18680,Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$36,800"

In [51]:
final_df = pd.get_dummies(final_df, columns=['brand', 'fuel_type'], drop_first=True)
final_df

,model_year,milage,engine,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,...,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“
0,2008,310.60262,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,"$10,000",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2022,25.74944,2.4L I4 16V GDI DOHC,"$26,599",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2012,112.65380,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,"$15,051",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2018,51.49888,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,"$20,999",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2021,46.67086,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$39,650",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,315.43064,235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$6,499",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4004,2013,117.48182,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,"$13,900",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4005,2020,70.81096,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$65,000",False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
4006,2021,38.62416,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$44,900",False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
4007,2019,32.18680,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$36,800",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [52]:
final_df['horsepower'] = final_df['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)
final_df['engine_L'] = final_df['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
final_df['cylinders'] = final_df['engine'].str.extract(r'([V|I]?(\d+))')[1].astype(float)
final_df.drop(columns=['engine'], inplace=True)

In [53]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,310.60262,"$10,000",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.0,3.2,258.0
1,2022,25.74944,"$26,599",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,NaN,2.4,2.0
2,2012,112.65380,"$15,051",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.0,3.7,305.0
3,2018,51.49888,"$20,999",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.0,2.4,201.0
4,2021,46.67086,"$39,650",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.0,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,315.43064,"$6,499",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.0,3.2,235.0
4004,2013,117.48182,"$13,900",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.0,2.5,227.0
4005,2020,70.81096,"$65,000",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.0,2.0,400.0
4006,2021,38.62416,"$44,900",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.0,2.0,400.0
4007,2019,32.18680,"$36,800",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.0,2.0,330.0

In [54]:
final_df.isna().sum()

model_year                   0
milage                       0
price                        0
brand_Alfa                   0
brand_Aston                  0
                          ...
fuel_type_not supported      0
fuel_type_â€“                  0
horsepower                 808
engine_L                   377
cylinders                   78
Length: 68, dtype: int64

In [55]:
final_df['horsepower'] = final_df['horsepower'].fillna(final_df['horsepower'].mean())

In [56]:
final_df.isna().sum()

model_year                   0
milage                       0
price                        0
brand_Alfa                   0
brand_Aston                  0
                          ...
fuel_type_not supported      0
fuel_type_â€“                  0
horsepower                   0
engine_L                   377
cylinders                   78
Length: 68, dtype: int64

In [57]:
final_df['engine_L'] = final_df['engine_L'].fillna(final_df['engine_L'].mean())

In [58]:
final_df.isna().sum()

model_year                  0
milage                      0
price                       0
brand_Alfa                  0
brand_Aston                 0
                           ..
fuel_type_not supported     0
fuel_type_â€“                 0
horsepower                  0
engine_L                    0
cylinders                  78
Length: 68, dtype: int64

In [59]:
final_df['cylinders'] = final_df['cylinders'].fillna(final_df['cylinders'].mean())

In [62]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,310.60262,"$10,000",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.000000,3.2,258.0
1,2022,25.74944,"$26,599",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,332.288437,2.4,2.0
2,2012,112.65380,"$15,051",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.000000,3.7,305.0
3,2018,51.49888,"$20,999",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.000000,2.4,201.0
4,2021,46.67086,"$39,650",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.000000,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,315.43064,"$6,499",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.000000,3.2,235.0
4004,2013,117.48182,"$13,900",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.000000,2.5,227.0
4005,2020,70.81096,"$65,000",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4006,2021,38.62416,"$44,900",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4007,2019,32.18680,"$36,800",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.000000,2.0,330.0

In [63]:
print(final_df[['milage']].head())
print(final_df['milage'].dtype)  # Should be float

      milage
0  310.60262
1   25.74944
2  112.65380
3   51.49888
4   46.67086
float64

In [64]:
final_df['milage'] = final_df['milage'].fillna(final_df['milage'].mean())

In [44]:
final_df

,model_year,milage,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,310.60262,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.000000,3.2,258.0
1,2022,25.74944,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,332.288437,2.4,2.0
2,2012,112.65380,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.000000,3.7,305.0
3,2018,51.49888,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.000000,2.4,201.0
4,2021,46.67086,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.000000,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,315.43064,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.000000,3.2,235.0
4004,2013,117.48182,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.000000,2.5,227.0
4005,2020,70.81096,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4006,2021,38.62416,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4007,2019,32.18680,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.000000,2.0,330.0

In [65]:
print(final_df.dtypes)

model_year                   int64
milage                     float64
price                       object
brand_Alfa                    bool
brand_Aston                   bool
                            ...
fuel_type_not supported       bool
fuel_type_â€“                   bool
horsepower                 float64
engine_L                   float64
cylinders                  float64
Length: 68, dtype: object

In [69]:
final_df['price'] = final_df['price'].replace(r'[\$,]', '', regex=True).astype(float)

In [70]:
final_df = final_df.astype(int)

In [71]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,310,10000,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,258,3,258
1,2022,25,26599,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,332,2,2
2,2012,112,15051,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,305,3,305
3,2018,51,20999,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,201,2,201
4,2021,46,39650,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,272,2,272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,315,6499,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,235,3,235
4004,2013,117,13900,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,227,2,227
4005,2020,70,65000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,400,2,400
4006,2021,38,44900,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,400,2,400
4007,2019,32,36800,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,330,2,330

In [72]:
X = final_df.drop(columns=['price']) 
y = final_df['price']

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [75]:
y_pred = model.predict(X_test)

In [76]:
y_pred

array([ 5.15229591e+03,  3.94547035e+04,  3.59667661e+04,  5.94869538e+02,
        6.75961444e+04,  5.76913598e+04,  2.28698952e+04,  6.24912438e+04,
        4.51152216e+04,  1.47455580e+04,  4.41946132e+04,  8.30326791e+04,
        4.92743819e+04,  4.17698446e+04,  6.94300139e+04,  4.22252887e+04,
        9.00341080e+03,  7.08776320e+03,  3.07024656e+05,  5.54590379e+04,
       -1.55264978e+03,  5.85121940e+04,  5.72467546e+04,  5.36193056e+04,
        3.41187572e+04,  2.35216012e+04,  4.41468638e+04,  5.47307275e+02,
        4.78821932e+04,  6.32950319e+04,  1.85748161e+04,  2.78886805e+04,
        3.68644360e+04,  2.95735030e+04,  4.60096805e+04,  4.01765375e+03,
        1.58685584e+04,  3.92896366e+04,  5.26702390e+04,  9.67524762e+04,
        4.72435893e+04,  7.42820107e+04,  4.67840242e+04,  4.27119090e+04,
        8.51149489e+04,  6.20191575e+04,  2.61903265e+04,  3.94357121e+04,
        9.85867900e+04,  3.56161779e+04,  3.93500842e+04,  5.07547120e+04,
        5.28725378e+04,  1.07794160e+05,  5.37686617e+04,  5.25899905e+04,
        4.66990267e+04,  4.31498444e+04,  6.28006741e+04,  2.20402099e+04,
        3.14369981e+04,  6.58031921e+03,  1.95443284e+04,  4.06949902e+05,
        9.15388393e+03,  4.82183310e+04,  7.15953274e+03,  6.54846037e+04,
        3.81393202e+04,  1.07024237e+04,  1.34106130e+05,  5.60779016e+04,
        1.55102872e+04,  3.76613620e+04,  4.70707200e+04, -3.08901215e+04,
        6.23179154e+04,  1.71439931e+03,  1.40511834e+04,  3.22292595e+04,
        1.12672085e+03,  2.27409513e+04,  3.60372880e+04,  6.64868095e+04,
        2.47564237e+04,  6.33226077e+04,  5.69790891e+04,  5.47477411e+04,
        1.64567388e+04,  2.61637641e+04,  2.80868233e+04,  3.12125861e+04,
        4.02152913e+04,  2.34962697e+04,  2.88406613e+04,  1.03227457e+04,
        1.33579654e+04,  2.26531333e+04,  5.85356454e+04,  1.71527708e+05,
        1.38820945e+04,  4.01542551e+04,  6.75563043e+04,  5.41479715e+04,
        3.54661061e+04,  1.06470806e+04,  4.02623319e+04,  3.31772760e+04,
        3.64085906e+04,  3.39087981e+04,  1.45502951e+04,  3.95821919e+04,
        6.50466788e+04,  3.70978342e+04,  3.85408767e+04,  5.34175554e+04,
        7.28239445e+03,  5.54442978e+04,  4.15388842e+04,  5.69009847e+04,
        2.04947356e+04,  4.85115070e+04,  7.06777716e+03,  4.81214916e+04,
        7.07684271e+03,  6.34646180e+04,  4.95050791e+04,  5.08381170e+04,
        6.78845931e+04,  5.90254007e+04,  2.47554416e+04,  4.47981673e+04,
        5.13088400e+04,  3.17727319e+04,  4.59997639e+04,  5.47705959e+04,
        6.91388434e+03,  1.28820165e+05,  1.47629145e+04,  6.93906181e+04,
        5.33157096e+04,  9.82219261e+03,  5.46066211e+04,  6.93826501e+04,
        4.84786030e+04,  6.28364709e+04,  5.07431928e+04, -1.72600140e+04,
       -1.28965669e+04,  4.56517332e+04,  2.57732361e+04,  4.11678465e+04,
        3.86018407e+04,  3.14028243e+05,  3.76846656e+04,  2.65382612e+04,
        2.68490141e+04,  1.22156731e+04,  1.21813842e+05,  4.34244655e+04,
        5.15749827e+04,  4.00265462e+05, -7.24468982e+03,  3.08798413e+04,
        2.61217631e+04,  5.88863602e+04,  2.50531563e+04,  5.42696597e+04,
        6.36174245e+04,  8.19919730e+03,  4.21063131e+04,  6.38846456e+04,
        3.31339190e+04,  9.21094540e+03,  5.75358682e+04,  5.35126232e+04,
        8.65605198e+04,  5.71753928e+04,  1.35257712e+04,  3.47909854e+04,
        6.00152371e+04,  1.34679215e+04,  4.00262564e+04,  7.09594394e+04,
        1.19345723e+04,  6.94065542e+04,  5.42786152e+04,  3.60877736e+04,
        2.00947542e+04,  6.16748797e+04,  2.86034525e+04,  3.98255805e+04,
        8.93659373e+04,  1.70362947e+04,  6.95599170e+04,  2.94588077e+04,
        1.88984846e+04,  4.97599625e+04,  3.55776267e+04, -3.02517629e+03,
        3.99292820e+04,  1.10738499e+04,  5.83834474e+04,  1.45592746e+04,
        3.32375033e+04,  6.27966308e+04,  2.29805064e+04,  4.62901439e+04,
        6.30923212e+04,  5.36657601e+04,  4.63680811e+04,  2.55989816e+04,
        1.40236146e+05,  5.65914381e+04, -2.82591944e+03,  3.03383512e+04,
        3.37908643e+04,  6.54183018e+04,  2.13383662e+04,  4.81382317e+04,
        5.96467981e+04,  3.40089520e+04,  3.17143162e+04,  6.75828264e+04,
        2.25920722e+04,  3.62892334e+03,  6.65268016e+04,  4.60068499e+04,
        3.68654459e+02,  6.93327215e+04,  3.06258944e+04,  5.66004313e+04,
        6.86780820e+04,  1.26665252e+04,  3.66727858e+04,  6.78846472e+04,
        2.61637641e+04,  3.57382938e+04,  6.54288275e+04,  5.11816483e+04,
        4.69586127e+04,  4.72364761e+04,  3.42725624e+04,  4.93841371e+04,
        1.53282611e+05,  4.39005574e+04,  4.25026519e+04,  2.55477039e+04,
        5.74596910e+04,  3.60206808e+04,  4.21657371e+04,  2.98680246e+04,
        2.95231166e+04,  4.16628397e+04,  1.57008361e+04,  2.81925948e+04,
        1.21352564e+04,  5.01408588e+04,  2.69046409e+04, -7.15849002e+03,
        2.37986492e+04,  2.36308542e+04,  2.47311356e+04,  3.42217801e+04,
        1.86254366e+04,  2.03920627e+04,  1.17311332e+04,  8.91932242e+03,
        3.09972908e+04,  4.66054611e+04,  3.66103145e+04,  4.99841672e+04,
        1.28297838e+04,  6.76784427e+04,  2.22547322e+04,  3.62297108e+04,
        4.06372535e+04,  6.49108975e+03,  3.67050623e+04,  5.54920320e+04,
        6.43833479e+04,  3.38769943e+04,  4.36519641e+04,  1.99421020e+04,
       -1.17445422e+04, -4.46822739e+03, -5.19129290e+03,  2.55463142e+04,
        5.27334149e+04,  1.15216105e+05,  4.76553480e+04,  7.70926607e+04,
        2.88377085e+04,  1.83621948e+04,  3.36635204e+04,  4.95484251e+03,
        3.44207919e+04,  5.87197884e+04,  5.28040176e+04,  2.06633668e+04,
        4.16721598e+04,  2.19435494e+04,  4.51427368e+04,  4.71296492e+04,
        6.36469412e+03,  4.45000784e+04,  7.59416221e+04,  1.08000909e+05,
        3.14519054e+04,  4.23470722e+04,  7.37068240e+04,  6.54759434e+04,
        8.63741668e+03,  6.46867208e+04,  2.26765325e+04,  8.37577955e+04,
        5.04645263e+04,  1.72268620e+04,  9.45307578e+03,  5.53478230e+04,
        3.18711214e+04,  4.29400667e+04,  6.32601731e+04,  3.62190250e+04,
        2.30936830e+03,  6.10747428e+04,  7.73368627e+04,  2.10701594e+04,
        2.47183752e+05,  1.15383029e+04,  3.05377596e+03, -9.11823467e+03,
        1.22490081e+04,  3.53033604e+04,  1.63813210e+04,  6.39842545e+04,
        7.50237475e+02,  1.24506529e+04,  3.72101555e+04,  4.52879743e+03,
        3.12144983e+04,  1.78058134e+04,  4.86469436e+04,  3.38732140e+04,
        2.16467159e+04,  4.10130515e+04,  5.49162648e+04, -3.13718799e+03,
        5.19739938e+04,  6.14435790e+04,  5.34830381e+04,  9.26366233e+04,
        1.89321434e+04,  1.04109177e+05,  6.22718562e+04,  1.43934574e+04,
        1.06062348e+04,  2.62886728e+03,  1.73258437e+05,  9.47235781e+03,
        3.16192339e+04,  3.66298204e+04,  4.71736348e+04,  2.57720218e+04,
        7.13599441e+04,  1.09074627e+04,  7.12085516e+04,  7.21029762e+03,
        1.30035039e+04,  8.69084754e+04,  1.20143274e+04,  3.83165384e+04,
        4.01329945e+04,  7.83374946e+04,  1.04698811e+05,  4.50755149e+04,
        6.32906299e+04,  3.54876388e+04,  1.00231958e+04,  4.25120898e+04,
        2.27135572e+04,  2.92735495e+04,  4.35770866e+04,  2.78580769e+04,
        5.69679821e+04,  8.12018818e+03,  2.94194667e+04,  1.90574565e+04,
        1.96395087e+04,  5.02370810e+04,  4.59870713e+04,  5.78499737e+04,
        2.27675268e+04,  4.50691485e+03,  3.69714030e+04,  3.10325408e+04,
        5.51872342e+04,  8.08040703e+03,  2.93672639e+04,  1.34385541e+04,
        1.45159415e+04,  5.16495354e+04,  5.28721704e+04,  6.01243877e+04,
        3.24683408e+04,  2.93252703e+04,  1.07544692e+04,  7.42660747e+04,
        5.66841948e+04,  3.71049271e+04,  3.50797825e+04,  4.84418430e+04,
        6.33069660e+04,  4.59166096e+04,  2.99322080e+04,  7.17151345e+04,
        6.33281553e+04,  2.09488953e+04,  1.20668994e+04,  7.38820115e+04,
        4.88322761e+04,  4.18559983e+04,  2.49089778e+05,  9.86106941e+04,
        2.94354027e+04,  4.42845179e+04,  2.40700407e+04,  4.67474303e+04,
        2.91359688e+04, -2.08497291e+03,  1.93875569e+04,  4.96556213e+03,
        1.07367391e+04,  7.21666612e+04,  5.72093824e+04,  2.65783881e+04,
        1.05913922e+04,  4.60362571e+04,  2.99638541e+04,  3.38170263e+04,
        6.16816810e+04,  5.11068986e+04,  4.27192584e+04,  2.42589671e+04,
        3.75052172e+04,  5.83778831e+04,  4.54959678e+04,  1.54263840e+04,
        5.70511429e+04,  3.13999427e+04,  1.70858480e+04,  1.58859077e+04,
        1.63632277e+04,  2.91722112e+04, -7.86171389e+03, -1.01157145e+01,
        1.34662701e+04,  4.50497320e+04,  5.48146947e+04,  1.46014543e+04,
        2.40657564e+04,  5.34972357e+04,  9.02363019e+04,  2.95760204e+04,
        6.89064448e+04,  4.25109830e+04,  5.20438583e+04,  6.32950319e+04,
       -8.56149174e+02,  4.78034765e+04,  2.65113346e+04,  8.46757604e+04,
        2.86952050e+04,  3.09484383e+04,  3.15833236e+04,  2.01296289e+04,
       -6.33688832e+03,  1.21335928e+04,  4.01033351e+04,  5.92825338e+04,
       -2.02898404e+04,  4.81892055e+04,  4.34911116e+04,  4.54546958e+04,
        6.31383351e+04,  4.45222927e+04,  1.66910465e+04,  1.14127649e+04,
        6.29114192e+04,  1.45930090e+04,  2.06690523e+04,  1.31145974e+04,
        8.77387920e+04,  3.05113424e+04,  6.80923301e+04,  7.65987970e+04,
        3.53909085e+04,  1.12155167e+05,  1.91680168e+04,  3.07968094e+04,
        2.52289829e+04,  9.85708540e+04,  3.98194467e+04,  3.01127503e+04,
        6.35280128e+04,  5.35459135e+04,  4.33679887e+04,  5.95814032e+04,
        3.87033216e+03,  2.76496398e+04,  5.10016230e+04,  2.33669375e+04,
        6.21375868e+03,  5.83842529e+04,  8.24358634e+04,  9.46976926e+04,
        1.59755096e+04,  6.34109421e+03,  4.44757505e+04,  4.10583090e+04,
        1.08040749e+05,  4.18742941e+04,  5.45876044e+04,  4.40901448e+04,
        5.36878005e+04,  6.19434643e+04,  3.38717485e+04,  1.77987545e+04,
        4.84849896e+04,  4.65926386e+04,  4.65049903e+04,  1.56510831e+04,
        1.60933316e+04,  3.14171108e+04,  3.97011733e+04,  7.01635572e+04,
        6.35138402e+04,  1.35635723e+05,  3.75553967e+04,  7.38820115e+04,
        5.39851221e+04,  9.29686056e+03,  1.63962297e+04,  1.10109608e+04,
        4.94590447e+04,  4.40863348e+04,  4.86043112e+04,  5.73016572e+04,
        3.19738565e+04,  3.18552662e+04,  7.64343278e+03,  3.69800938e+04,
        1.54569132e+04,  1.75094480e+04,  3.53865828e+03,  1.64803729e+04,
        1.73226565e+05,  4.29407440e+04,  5.73304448e+04,  6.08473803e+04,
        5.20714646e+04,  8.77172842e+04,  6.59027647e+04, -1.84196307e+03,
        4.09234802e+04,  1.06424862e+04,  4.17500354e+04,  5.91081423e+04,
        3.49031169e+04,  9.47375327e+04,  1.06468193e+05,  5.44539117e+04,
        9.27411966e+02,  3.27599406e+05,  6.60451619e+03,  4.85077444e+04,
        1.77773879e+04,  2.28457287e+05,  6.28803544e+04,  7.36191758e+04,
        9.16177729e+03,  8.26104646e+04,  1.85217077e+04,  7.21132131e+04,
        3.57343122e+04,  3.63426934e+03,  6.40470370e+04,  8.74678792e+04,
        2.97098490e+04, -7.83329585e+03,  9.69173150e+04,  9.38364776e+03,
        1.04356186e+05,  4.86877871e+04,  6.86108621e+04, -3.05933009e+03,
        1.09408647e+05,  3.93055727e+04,  6.67458388e+04,  3.89957631e+04,
        7.59151069e+04,  2.93164373e+05,  9.57699868e+04,  1.68017688e+04,
        4.90766947e+04,  9.63611630e+03,  5.93918214e+04,  5.30439280e+04,
        5.70944886e+04,  3.23996787e+04,  2.23688504e+04,  4.84626696e+04,
        4.05406126e+04,  3.77808634e+04,  5.93921718e+04, -8.27061622e+03,
        4.53162062e+04,  1.86989774e+04,  1.22957509e+04,  5.96876640e+04,
        2.92495559e+04,  6.32869124e+03,  4.22319900e+04,  6.78769956e+04,
        6.56636664e+04,  9.67604442e+04,  6.46763997e+04,  3.01155591e+04,
        5.71316919e+04,  3.43462076e+04,  2.86835692e+04,  3.04419355e+04,
        3.70457469e+04,  6.24486611e+04,  8.48986127e+04,  3.16442793e+04,
        5.25186668e+04,  3.65621075e+04,  1.34491712e+04,  5.42849969e+04,
        7.63447395e+03,  1.06565398e+05,  4.86096621e+04,  1.04654109e+04,
        4.16590729e+04, -2.73082020e+02,  7.65510850e+04,  2.78612269e+04,
        2.65071179e+04,  1.64724913e+04,  2.16760558e+04,  2.89533056e+04,
        3.17224367e+04,  1.85022818e+04,  4.90716928e+04,  5.08545920e+04,
        2.74432617e+04,  6.51786436e+04,  1.52580940e+04, -8.08141604e+03,
        4.79618734e+04,  2.17315257e+04,  5.26877605e+04,  3.06200324e+04,
        4.31552034e+04,  8.79875834e+04,  9.45134773e+03,  7.90035674e+04,
        4.56234562e+04,  3.58860399e+04,  5.36787517e+04,  4.26649111e+04,
        2.89653550e+04,  7.55750931e+04,  1.67222121e+04,  4.04265838e+04,
        8.89910127e+03,  3.10670732e+04,  6.50245585e+04,  4.06951409e+04,
        3.66884001e+04,  6.04667320e+02,  3.93721693e+04,  7.73372102e+04,
        5.60265019e+04,  2.80890310e+05, -2.09645962e+03,  7.65824016e+04,
        5.38083077e+04,  3.45702021e+04,  4.54505791e+04,  1.57159689e+04,
        2.91429083e+04,  1.61591208e+04,  1.39810810e+05,  1.01902862e+05,
        5.78365953e+04,  1.20048681e+04,  6.93029699e+04,  4.48437345e+03,
        5.62563534e+04,  4.30802578e+04,  4.86621644e+04, -3.35711410e+03,
        4.07465323e+04,  2.39216863e+04, -2.53998952e+03,  4.22054979e+04,
        6.86794464e+04,  3.56132909e+04,  4.32653243e+04,  3.55585355e+04,
        3.87638087e+04,  2.04628218e+04,  5.11938345e+04,  1.62423406e+04,
        5.34862440e+03,  1.58239270e+05,  2.72771155e+04,  3.66656918e+04,
        4.67943858e+04,  2.14707233e+04,  1.09217976e+04,  7.89680120e+04,
        6.22242843e+04,  1.47716508e+04,  6.29135490e+04,  2.69850308e+04,
        4.18826637e+04,  2.28061510e+04,  7.82440554e+03,  2.58186167e+04,
        5.02953994e+04,  4.74712013e+04,  3.54179741e+04,  6.86181759e+04,
        5.15670147e+04,  4.71777036e+04,  1.03875725e+05,  6.46881178e+04,
        6.92956626e+04,  1.86658353e+04,  3.73127702e+04,  4.12075532e+04,
        1.18910962e+04, -1.67328319e+04,  5.55297600e+04,  4.99053063e+04,
        3.42494368e+04,  2.83519552e+04,  3.76970145e+04,  2.21802229e+03,
        2.93215414e+05,  1.05832340e+05,  3.01206345e+04,  6.72863532e+04,
        1.87527804e+04,  3.11947226e+04,  6.34225203e+04,  7.23677422e+03,
        1.65544602e+04,  2.45546976e+04,  5.41801069e+04,  3.54807167e+04,
        1.60442194e+04,  3.81867971e+04,  4.46714736e+04,  5.45477643e+04,
        3.67639979e+04,  1.53578473e+04,  4.58525934e+04,  7.52067142e+04,
        4.52472373e+04,  3.61126493e+04,  6.56110988e+04,  1.15318156e+05,
        3.41128397e+04,  4.48132558e+04,  3.45831635e+04,  5.26384824e+03,
       -1.04999916e+03,  6.01881319e+04,  9.39799707e+04,  3.55014885e+04,
        3.85363791e+04,  3.24842769e+04,  4.67522892e+04,  5.77733488e+04,
        3.95314545e+05,  7.49027691e+03,  4.40807453e+04,  7.02868672e+04,
        5.17273073e+03,  1.45761381e+05,  9.63481421e+04,  2.21625280e+04,
        1.61359916e+04,  4.18687836e+04,  9.23475192e+03,  2.98207220e+04,
        6.37449129e+04,  5.95507378e+04])

In [77]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"ðŸ“Š Model Evaluation:")
print(f"MAE  (Mean Absolute Error)  : {mae:.2f}")
print(f"MSE  (Mean Squared Error)   : {mse:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"RÂ² Score                    : {r2:.4f}")

ðŸ“Š Model Evaluation:
MAE  (Mean Absolute Error)  : 17401.29
MSE  (Mean Squared Error)   : 1144959506.70
RMSE (Root Mean Squared Error): 33837.25
RÂ² Score                    : 0.4977

In [78]:
coefficients = pd.DataFrame({'Feature': X.columns, 'Coefficient': model.coef_})
coefficients.sort_values(by='Coefficient', ascending=False, inplace=True)
print(coefficients)

                    Feature   Coefficient
7             brand_Bugatti  1.887369e+06
47        brand_Rolls-Royce  3.404824e+05
26        brand_Lamborghini  2.439926e+05
14            brand_Ferrari  2.002624e+05
36            brand_McLaren  1.583339e+05
..                      ...           ...
11           brand_Chrysler -6.738831e+03
21           brand_INFINITI -8.029149e+03
45                brand_RAM -1.239419e+04
58  fuel_type_E85 Flex Fuel -1.609758e+04
62  fuel_type_not supported -1.679324e+04

[67 rows x 2 columns]

In [79]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)
y_pred_poly = model_poly.predict(X_test_poly)

In [80]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"ðŸ“Š Model Evaluation:")
print(f"MAE  (Mean Absolute Error)  : {mae:.2f}")
print(f"MSE  (Mean Squared Error)   : {mse:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"RÂ² Score                    : {r2:.4f}")

ðŸ“Š Model Evaluation:
MAE  (Mean Absolute Error)  : 17401.29
MSE  (Mean Squared Error)   : 1144959506.70
RMSE (Root Mean Squared Error): 33837.25
RÂ² Score                    : 0.4977

In [81]:
import numpy as np
final_df['price'] = np.log1p(final_df['price'])  # log1p avoids log(0) issues

In [82]:
final_df['car_age'] = 2025 - final_df['model_year']  
final_df.drop(columns=['model_year'], inplace=True)

In [84]:
final_df['mileage_per_year'] = final_df['milage'] / final_df['car_age']
final_df['mileage_per_year'] = final_df['mileage_per_year'].fillna(final_df['milage'])

In [86]:
final_df['hp_per_liter'] = final_df['horsepower'] / final_df['engine_L']
final_df['hp_per_liter'] = final_df['hp_per_liter'].fillna(final_df['horsepower'])

In [97]:
final_df.drop(columns=['horsepower','milage'],inplace=True)

KeyError: "['horsepower', 'milage'] not found in axis"

In [91]:
final_df

,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,...,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,engine_L,cylinders,car_age,mileage_per_year,hp_per_liter
0,9.210440,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,258,17,18.235294,86.000000
1,10.188666,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,2,3,8.333333,166.000000
2,9.619266,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,305,13,8.615385,101.666667
3,9.952278,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,201,7,7.285714,100.500000
4,10.587871,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,272,4,11.500000,136.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,8.779557,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,235,17,18.529412,78.333333
4004,9.539716,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,227,12,9.750000,113.500000
4005,11.082158,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,5,14.000000,200.000000
4006,10.712215,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,4,9.500000,200.000000
4007,10.513280,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,330,6,5.333333,165.000000

In [92]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
X = final_df.drop(columns=['price'])
y = final_df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"ðŸ“Š Model Evaluation AFTER Feature Engineering:")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"RÂ² Score : {r2:.4f}")

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [95]:
print(df.describe())

        model_year      milage
count  4008.000000  4008.00000
mean   2015.517465   113.86201
std       6.104423   122.19128
min    1974.000000     1.60934
25%    2012.000000    38.62416
50%    2017.000000    86.90436
75%    2020.000000   154.49664
max    2024.000000  1591.63726

In [99]:
print(final_df.isnull().sum())
print(final_df.isin([np.inf, -np.inf]).sum())

price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64
price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        5
Length: 68, dtype: int64

In [101]:
final_df.replace([np.inf, -np.inf], np.nan, inplace=True)  
final_df.fillna(final_df.mean(), inplace=True)

In [102]:
final_df

,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,...,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,engine_L,cylinders,car_age,mileage_per_year,hp_per_liter
0,9.210440,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,258,17,18.235294,86.000000
1,10.188666,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,2,3,8.333333,166.000000
2,9.619266,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,305,13,8.615385,101.666667
3,9.952278,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,201,7,7.285714,100.500000
4,10.587871,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,272,4,11.500000,136.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,8.779557,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,235,17,18.529412,78.333333
4004,9.539716,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,227,12,9.750000,113.500000
4005,11.082158,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,5,14.000000,200.000000
4006,10.712215,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,4,9.500000,200.000000
4007,10.513280,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,330,6,5.333333,165.000000

In [103]:
print(final_df.isnull().sum())
print(final_df.isin([np.inf, -np.inf]).sum())

price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64
price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64

In [104]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
X = final_df.drop(columns=['price'])
y = final_df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"ðŸ“Š Model Evaluation AFTER Feature Engineering:")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"RÂ² Score : {r2:.4f}")

ðŸ“Š Model Evaluation AFTER Feature Engineering:
MAE  : 0.32
MSE  : 0.19
RMSE : 0.44
RÂ² Score : 0.7306

In [105]:
y_pred = model.predict(X_test) 
results = pd.DataFrame({'Actual Price': y_test, 'Predicted Price': y_pred})
print(results.head())

      Actual Price  Predicted Price
2580      9.609184         9.127860
3659     10.373522        10.511585
897       9.680406        10.319929
2091      9.433564         9.088446
1044     11.361986        11.229812

In [109]:
import joblib
joblib.dump(model, "car_price_model.pkl")
feature_names = X_train.columns.tolist()
joblib.dump(feature_names, "feature_names.pkl")

['feature_names.pkl']

In [108]:
import streamlit as st
import joblib
import pandas as pd
model = joblib.load("car_price_model.pkl")
st.title("ðŸš— Car Price Prediction App")
model_year = st.number_input("Model Year", min_value=2000, max_value=2025, step=1)
milage = st.number_input("Mileage (in thousands)", min_value=0.0)
horsepower = st.number_input("Horsepower")
engine_L = st.number_input("Engine Size (L)")
cylinders = st.number_input("Cylinders", min_value=2, max_value=16, step=1)
if st.button("Predict Price"):
    data = pd.DataFrame([{
        "model_year": model_year,
        "milage": milage,
        "horsepower": horsepower,
        "engine_L": engine_L,
        "cylinders": cylinders
    }])
    data = data[X_train.columns]
    price = model.predict(data)[0]
    st.success(f"ðŸ’° Predicted Price: ${price:,.2f}")

2025-02-26 12:37:38.755 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.393
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\archit vaishnav\AppData\Local\Programs\Python\Python312\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-02-26 12:37:39.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.405 Session state does not function when running a script without `streamlit run`
2025-02-26 12:37:39.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-26 12:37:39.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [110]:
final_df.head(5)

,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,...,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,engine_L,cylinders,car_age,mileage_per_year,hp_per_liter
0,9.210440,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,258,17,18.235294,86.000000
1,10.188666,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,2,3,8.333333,166.000000
2,9.619266,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,305,13,8.615385,101.666667
3,9.952278,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,201,7,7.285714,100.500000
4,10.587871,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,272,4,11.500000,136.000000