In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('used_cars.csv')

In [3]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [4]:
df.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [5]:
df.drop(columns=['clean_title'],inplace=True)

In [6]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [7]:
df['fuel_type'] = df['fuel_type'].fillna('Battery')
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [8]:
df.fillna({'accident': 'No accident'}, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,None reported,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,"$40,000"

In [9]:
df['accident'] = df['accident'].str.strip().replace({'None Reported': 'No Accident'},inplace=True)

In [10]:
df.drop(columns=['accident'],inplace=True)

In [11]:
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,"$34,999"
...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",Battery,Electric,Automatic,Black,Black,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,"$40,000"

In [12]:
df.sort_values(by='brand', ascending=True, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
1537,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
902,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2536,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
2556,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
885,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
718,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
514,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
3474,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
3369,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"
2261,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,"$5,000"

In [13]:
df = df.reset_index(drop=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
1,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
3,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
4,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
4004,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
4005,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
4006,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
4007,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"
4008,smart,ForTwo Pure,2008,"61,595 mi.",Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,"$5,000"

In [14]:
df.drop(index=4008, inplace=True)
df

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,price
0,Acura,TL 3.2,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$10,000"
1,Acura,ILX Premium Package,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Gray,Ebony,"$26,599"
2,Acura,TL 3.7,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$15,051"
3,Acura,ILX Premium Package,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Black,Black,"$20,999"
4,Acura,RDX Advance Package,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,"$39,650"
...,...,...,...,...,...,...,...,...,...,...
4003,Volvo,XC90 3.2,2008,"196,000 mi.",Gasoline,235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,A/T,Black,Beige,"$6,499"
4004,Volvo,C30 T5 Premier Plus,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$13,900"
4005,Volvo,XC90 Hybrid T8 Inscription,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Blue,Brown,"$65,000"
4006,Volvo,S60 Recharge Plug-In Hybrid T8 Inscription,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,"$44,900"
4007,Volvo,XC60 T6 Inscription,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,"$36,800"

In [15]:
df.isna().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
price           0
dtype: int64

In [16]:
selected_columns = ['brand', 'model_year', 'milage', 'fuel_type', 'engine','price']
final_df = df[selected_columns]

In [17]:
final_df

,brand,model_year,milage,fuel_type,engine,price
0,Acura,2008,"193,783 mi.",Gasoline,258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,"$10,000"
1,Acura,2022,"16,120 mi.",Gasoline,2.4L I4 16V GDI DOHC,"$26,599"
2,Acura,2012,"70,000 mi.",Gasoline,305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,"$15,051"
3,Acura,2018,"32,260 mi.",Gasoline,201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,"$20,999"
4,Acura,2021,"29,000 mi.",Gasoline,272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$39,650"
...,...,...,...,...,...,...
4003,Volvo,2008,"196,000 mi.",Gasoline,235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$6,499"
4004,Volvo,2013,"73,000 mi.",Gasoline,227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,"$13,900"
4005,Volvo,2020,"44,487 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$65,000"
4006,Volvo,2021,"24,158 mi.",Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$44,900"
4007,Volvo,2019,"20,623 mi.",Gasoline,330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$36,800"

In [18]:
final_df = pd.get_dummies(final_df, columns=['brand', 'fuel_type'], drop_first=True)
final_df

,model_year,milage,engine,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,...,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“
0,2008,"193,783 mi.",258.0HP 3.2L V6 Cylinder Engine Gasoline Fuel,"$10,000",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2022,"16,120 mi.",2.4L I4 16V GDI DOHC,"$26,599",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,2012,"70,000 mi.",305.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,"$15,051",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2018,"32,260 mi.",201.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,"$20,999",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2021,"29,000 mi.",272.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$39,650",False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,"196,000 mi.",235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$6,499",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4004,2013,"73,000 mi.",227.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,"$13,900",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4005,2020,"44,487 mi.",400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$65,000",False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
4006,2021,"24,158 mi.",400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$44,900",False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
4007,2019,"20,623 mi.",330.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$36,800",False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [19]:
final_df['horsepower'] = final_df['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)
final_df['engine_L'] = final_df['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
final_df['cylinders'] = final_df['engine'].str.extract(r'([V|I]?(\d+))')[1].astype(float)
final_df.drop(columns=['engine'], inplace=True)

In [20]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,"193,783 mi.","$10,000",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.0,3.2,258.0
1,2022,"16,120 mi.","$26,599",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,NaN,2.4,2.0
2,2012,"70,000 mi.","$15,051",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.0,3.7,305.0
3,2018,"32,260 mi.","$20,999",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.0,2.4,201.0
4,2021,"29,000 mi.","$39,650",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.0,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,"196,000 mi.","$6,499",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.0,3.2,235.0
4004,2013,"73,000 mi.","$13,900",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.0,2.5,227.0
4005,2020,"44,487 mi.","$65,000",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.0,2.0,400.0
4006,2021,"24,158 mi.","$44,900",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.0,2.0,400.0
4007,2019,"20,623 mi.","$36,800",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.0,2.0,330.0

In [21]:
final_df.isna().sum()

model_year                   0
milage                       0
price                        0
brand_Alfa                   0
brand_Aston                  0
                          ...
fuel_type_not supported      0
fuel_type_â€“                  0
horsepower                 808
engine_L                   377
cylinders                   78
Length: 68, dtype: int64

In [22]:
final_df['horsepower'] = final_df['horsepower'].fillna(final_df['horsepower'].mean())

In [23]:
final_df.isna().sum()

model_year                   0
milage                       0
price                        0
brand_Alfa                   0
brand_Aston                  0
                          ...
fuel_type_not supported      0
fuel_type_â€“                  0
horsepower                   0
engine_L                   377
cylinders                   78
Length: 68, dtype: int64

In [24]:
final_df['engine_L'] = final_df['engine_L'].fillna(final_df['engine_L'].mean())

In [25]:
final_df.isna().sum()

model_year                  0
milage                      0
price                       0
brand_Alfa                  0
brand_Aston                 0
                           ..
fuel_type_not supported     0
fuel_type_â€“                 0
horsepower                  0
engine_L                    0
cylinders                  78
Length: 68, dtype: int64

In [26]:
final_df['cylinders'] = final_df['cylinders'].fillna(final_df['cylinders'].mean())

In [27]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,"193,783 mi.","$10,000",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.000000,3.2,258.0
1,2022,"16,120 mi.","$26,599",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,332.288437,2.4,2.0
2,2012,"70,000 mi.","$15,051",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.000000,3.7,305.0
3,2018,"32,260 mi.","$20,999",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.000000,2.4,201.0
4,2021,"29,000 mi.","$39,650",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.000000,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,"196,000 mi.","$6,499",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.000000,3.2,235.0
4004,2013,"73,000 mi.","$13,900",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.000000,2.5,227.0
4005,2020,"44,487 mi.","$65,000",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4006,2021,"24,158 mi.","$44,900",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4007,2019,"20,623 mi.","$36,800",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.000000,2.0,330.0

In [28]:
print(final_df[['milage']].head())
print(final_df['milage'].dtype)  # Should be float

        milage
0  193,783 mi.
1   16,120 mi.
2   70,000 mi.
3   32,260 mi.
4   29,000 mi.
object

In [29]:
final_df['milage'] = final_df['milage'].fillna(final_df['milage'].mean())

TypeError: Could not convert string '193,783 mi.16,120 mi.70,000 mi.32,260 mi.29,000 mi.32,500 mi.116,500 mi.61,000 mi.120,000 mi.2,118 mi.122,000 mi.36,267 mi.106,335 mi.123,000 mi.3,959 mi.97,700 mi.79,884 mi.123,000 mi.183,455 mi.198,000 mi.13,600 mi.199,296 mi.89,190 mi.6,523 mi.116,000 mi.3,574 mi.4,700 mi.3,708 mi.75,000 mi.37,900 mi.25,779 mi.68,425 mi.14,896 mi.68,200 mi.128,000 mi.75,980 mi.137,200 mi.38,000 mi.56,778 mi.40,000 mi.80,000 mi.3,389 mi.44,457 mi.151,600 mi.187,883 mi.6,900 mi.102,665 mi.15,895 mi.111,650 mi.1,798 mi.136,397 mi.186,040 mi.20,750 mi.165,000 mi.71,400 mi.90,605 mi.184,421 mi.31,015 mi.132,252 mi.3,415 mi.30,177 mi.19,500 mi.16,878 mi.45,000 mi.41,000 mi.1,966 mi.48,000 mi.9,275 mi.39,615 mi.28,644 mi.21,400 mi.26,500 mi.21,487 mi.56,910 mi.50,000 mi.10,558 mi.6,645 mi.2,000 mi.30,000 mi.23,339 mi.18,665 mi.37,045 mi.36,000 mi.62,378 mi.25,025 mi.14,900 mi.2,353 mi.22,770 mi.2,165 mi.1,023 mi.25,991 mi.21,100 mi.156,875 mi.74,030 mi.61,258 mi.12,245 mi.8,193 mi.14,724 mi.99,769 mi.26,500 mi.91,188 mi.69,300 mi.90,236 mi.14,750 mi.28,927 mi.77,000 mi.67,035 mi.35,850 mi.129,567 mi.33,000 mi.61,450 mi.139,355 mi.42,650 mi.74,000 mi.89,500 mi.54,900 mi.13,895 mi.181,000 mi.75,965 mi.98,400 mi.202,000 mi.2,425 mi.4,100 mi.83,420 mi.60,251 mi.90,360 mi.1,900 mi.67,900 mi.96,238 mi.61,000 mi.207,000 mi.4,457 mi.12,000 mi.103,272 mi.125,000 mi.118,500 mi.21,800 mi.111,773 mi.53,000 mi.9,325 mi.35,000 mi.18,031 mi.106,000 mi.6,682 mi.39,000 mi.83,000 mi.72,000 mi.153,000 mi.17,377 mi.25,300 mi.23,827 mi.39,600 mi.142,666 mi.54,300 mi.41,856 mi.39,000 mi.49,098 mi.93,400 mi.126,000 mi.49,500 mi.35,580 mi.35,999 mi.38,718 mi.18,603 mi.39,071 mi.63,400 mi.108,000 mi.48,500 mi.33,012 mi.52,105 mi.45,843 mi.16,000 mi.49,000 mi.31,500 mi.73,837 mi.104,457 mi.111,564 mi.72,865 mi.7,874 mi.50,000 mi.27,100 mi.22,800 mi.73,000 mi.29,294 mi.4,648 mi.137,000 mi.44,000 mi.55,000 mi.50,400 mi.79,500 mi.13,133 mi.96,000 mi.51,000 mi.16,400 mi.8,497 mi.68,000 mi.64,800 mi.25,000 mi.36,500 mi.43,238 mi.126,760 mi.10,601 mi.15,000 mi.91,403 mi.28,211 mi.45,900 mi.54,700 mi.11,322 mi.27,532 mi.23,350 mi.8,940 mi.14,739 mi.81,880 mi.54,000 mi.55,564 mi.41,000 mi.250 mi.34,300 mi.10,120 mi.3,158 mi.21,832 mi.53,900 mi.25,361 mi.71,280 mi.1,156 mi.108,000 mi.35,322 mi.49,650 mi.82,000 mi.66,150 mi.51,984 mi.75,000 mi.6,397 mi.9,628 mi.7,300 mi.38,360 mi.125,575 mi.87,066 mi.5,682 mi.83,500 mi.68,000 mi.6,046 mi.119,000 mi.18,100 mi.92,203 mi.14,550 mi.10,832 mi.70,773 mi.52,500 mi.24,500 mi.66,250 mi.98,527 mi.69,700 mi.102,370 mi.96,800 mi.21,240 mi.24,500 mi.73,000 mi.13,566 mi.124,747 mi.22,588 mi.146,500 mi.72,922 mi.42,400 mi.84,000 mi.64,549 mi.111,000 mi.9,835 mi.59,715 mi.137,273 mi.10,900 mi.22,300 mi.78,124 mi.151,400 mi.96,273 mi.10,071 mi.90,818 mi.18,099 mi.63,398 mi.12,000 mi.54,900 mi.6,581 mi.47,523 mi.20,675 mi.37,500 mi.93,000 mi.155,382 mi.91,877 mi.60,000 mi.23,823 mi.30,000 mi.153,000 mi.9,472 mi.117,000 mi.4,514 mi.37,000 mi.52,375 mi.73,000 mi.135,000 mi.109,330 mi.67,500 mi.114,890 mi.27,654 mi.27,214 mi.78,500 mi.83,000 mi.29,400 mi.117,660 mi.13,700 mi.59,257 mi.65,000 mi.89,000 mi.15,000 mi.110,000 mi.65,550 mi.19,600 mi.2,900 mi.72,277 mi.30,309 mi.105,000 mi.124 mi.40,989 mi.32,000 mi.80,211 mi.31,157 mi.11,102 mi.34,455 mi.38,352 mi.39,886 mi.72,900 mi.22,655 mi.82,000 mi.48,000 mi.106,000 mi.132,000 mi.120,000 mi.28,898 mi.23,700 mi.7,758 mi.86,500 mi.79,995 mi.135,000 mi.33,749 mi.1,120 mi.3,099 mi.8,000 mi.94,500 mi.185,000 mi.114,528 mi.77,800 mi.26,000 mi.46,150 mi.95,450 mi.1,160 mi.45,253 mi.41,550 mi.37,000 mi.169,000 mi.5,338 mi.48,291 mi.46,000 mi.77,750 mi.86,629 mi.119,750 mi.7,121 mi.10,376 mi.34,800 mi.7,000 mi.33,214 mi.133,500 mi.19,300 mi.90,347 mi.3,500 mi.125,470 mi.18,362 mi.22,500 mi.52,500 mi.38,671 mi.125,500 mi.15,889 mi.96,000 mi.23,195 mi.178,000 mi.31,100 mi.60,255 mi.143,250 mi.25,793 mi.55,250 mi.41,000 mi.65,852 mi.18,421 mi.7,580 mi.99,700 mi.67,874 mi.74,381 mi.28,000 mi.81,000 mi.14,806 mi.31,850 mi.137,825 mi.125,000 mi.204,884 mi.36,905 mi.22,700 mi.3,213 mi.66,500 mi.61,000 mi.41,048 mi.17,900 mi.129,999 mi.53,814 mi.86,000 mi.31,500 mi.51,000 mi.13,000 mi.83,298 mi.1,500 mi.76,309 mi.13,250 mi.4,200 mi.15,097 mi.69,764 mi.7,200 mi.25,520 mi.37,100 mi.82,000 mi.91,798 mi.59,000 mi.60,000 mi.48,000 mi.37,000 mi.44,000 mi.27,965 mi.41,906 mi.10,426 mi.5,541 mi.57,939 mi.61,773 mi.25,013 mi.98,000 mi.94,653 mi.35,400 mi.72,000 mi.23,430 mi.74,000 mi.84,709 mi.98,200 mi.92,000 mi.43,000 mi.120,000 mi.18,000 mi.134,000 mi.41,000 mi.3,490 mi.177,700 mi.5,018 mi.816 mi.33,499 mi.29,553 mi.98,000 mi.29,025 mi.81,000 mi.90,000 mi.25,000 mi.59,000 mi.77,000 mi.60,100 mi.76,474 mi.94,000 mi.123,000 mi.30,000 mi.91,545 mi.10,950 mi.92,008 mi.36,000 mi.98,600 mi.45,090 mi.21,000 mi.132,000 mi.29,140 mi.9,000 mi.76,465 mi.36,750 mi.8,307 mi.24,650 mi.4,106 mi.72,700 mi.54,293 mi.71,000 mi.75,479 mi.184,700 mi.127,273 mi.74,600 mi.59,000 mi.25,000 mi.7,982 mi.126,000 mi.500 mi.19,300 mi.14,269 mi.72,903 mi.16,307 mi.65,000 mi.24,300 mi.25,108 mi.81,500 mi.58,664 mi.78,414 mi.50,000 mi.60,000 mi.124,000 mi.40,000 mi.206,000 mi.105,100 mi.31,350 mi.45,241 mi.4,880 mi.51,983 mi.126,500 mi.33,500 mi.55,000 mi.118,000 mi.61,145 mi.54,000 mi.45,000 mi.34,967 mi.75,500 mi.15,882 mi.39,960 mi.15,736 mi.47,700 mi.56,235 mi.153,600 mi.111,000 mi.43,000 mi.14,360 mi.19,473 mi.53,600 mi.31,090 mi.70,700 mi.20,500 mi.35,000 mi.68,500 mi.33,000 mi.73,000 mi.43,000 mi.49,700 mi.11,078 mi.37,426 mi.27,989 mi.41,000 mi.50,100 mi.26,600 mi.132,200 mi.26,000 mi.82,849 mi.63,150 mi.13,735 mi.4,348 mi.45,076 mi.92,040 mi.69,750 mi.122,141 mi.135,000 mi.58,000 mi.18,200 mi.35,248 mi.43,000 mi.846 mi.44,261 mi.142,000 mi.39,250 mi.23,647 mi.39,300 mi.33,000 mi.70,000 mi.58,880 mi.40,080 mi.112,000 mi.98,500 mi.86,000 mi.190,395 mi.62,500 mi.40,000 mi.9,949 mi.110,000 mi.2,010 mi.83,000 mi.28,744 mi.41,500 mi.73,500 mi.29,500 mi.91,420 mi.122,600 mi.46,508 mi.18,651 mi.36,438 mi.117,200 mi.57,550 mi.74,500 mi.76,009 mi.2,437 mi.12,800 mi.91,500 mi.85,252 mi.103,990 mi.75,000 mi.65,800 mi.67,000 mi.27,158 mi.125,450 mi.100,780 mi.9,670 mi.60,942 mi.456 mi.103,000 mi.8,500 mi.98,000 mi.10,917 mi.52,253 mi.19,069 mi.2,492 mi.30,450 mi.59,203 mi.36,812 mi.20,500 mi.57,800 mi.42,200 mi.15,000 mi.25,500 mi.3,950 mi.25,918 mi.85,095 mi.87,000 mi.69,000 mi.27,000 mi.21,057 mi.138,000 mi.28,200 mi.9,200 mi.14,993 mi.25,990 mi.28,000 mi.92,984 mi.27,000 mi.76,400 mi.38,000 mi.140,000 mi.52,000 mi.79,341 mi.25,348 mi.85,766 mi.16,900 mi.2,950 mi.82,978 mi.59,300 mi.66,690 mi.45,800 mi.10,906 mi.74,850 mi.12,500 mi.242,000 mi.34,000 mi.70,582 mi.16,975 mi.68,750 mi.35,035 mi.18,500 mi.22,001 mi.79,089 mi.27,858 mi.10,972 mi.57,800 mi.31,875 mi.79,422 mi.20,200 mi.18,000 mi.1,919 mi.24,500 mi.18,950 mi.8,332 mi.69,600 mi.714 mi.15,109 mi.43,000 mi.32,500 mi.31,500 mi.7,960 mi.14,684 mi.27,404 mi.16,146 mi.55,050 mi.1,335 mi.22,039 mi.33,000 mi.1,795 mi.2,600 mi.41,000 mi.61,160 mi.72,166 mi.6,330 mi.55,403 mi.121,521 mi.87,555 mi.110,000 mi.27,340 mi.139,105 mi.83,280 mi.103,814 mi.18,185 mi.53,000 mi.119,500 mi.170,000 mi.32,000 mi.31,181 mi.19,079 mi.28,548 mi.68,653 mi.50,000 mi.68,325 mi.134,655 mi.35,569 mi.36,544 mi.86,281 mi.147,589 mi.89,726 mi.67,500 mi.20,104 mi.47,839 mi.125,559 mi.190,000 mi.45,000 mi.4,500 mi.72,060 mi.53,169 mi.2,415 mi.114,500 mi.136,150 mi.94,155 mi.63,172 mi.48,613 mi.48,600 mi.4,283 mi.62,500 mi.22,187 mi.8,532 mi.160,249 mi.35,566 mi.119,000 mi.69,289 mi.159,500 mi.19,250 mi.120,000 mi.113,000 mi.74,414 mi.113,395 mi.104,000 mi.4,451 mi.152,068 mi.93,971 mi.62,950 mi.35,200 mi.95,570 mi.55,000 mi.15,689 mi.110,000 mi.168,600 mi.8,074 mi.69,423 mi.80,400 mi.31,500 mi.28,121 mi.20,296 mi.49,620 mi.46,000 mi.44,500 mi.90,000 mi.34,988 mi.59,000 mi.46,711 mi.222 mi.105,760 mi.72,843 mi.15,350 mi.116,500 mi.66,500 mi.96,000 mi.112,000 mi.25,000 mi.74,150 mi.49,273 mi.64,800 mi.54,002 mi.134,000 mi.146,200 mi.70,503 mi.38,500 mi.225,000 mi.3,000 mi.85,000 mi.191,900 mi.83,000 mi.92,000 mi.11,459 mi.155,000 mi.1,090 mi.54,259 mi.6,090 mi.600 mi.124,542 mi.130,000 mi.61,549 mi.94,100 mi.81,696 mi.24,114 mi.150,000 mi.48,000 mi.56,860 mi.99,897 mi.44,692 mi.26,000 mi.66,200 mi.32,000 mi.36,500 mi.99,000 mi.87,500 mi.123,000 mi.71,000 mi.8,044 mi.152,000 mi.47,000 mi.92,000 mi.53,450 mi.67,726 mi.54,323 mi.105,000 mi.89,700 mi.69,001 mi.89,000 mi.53,100 mi.134,500 mi.148,377 mi.98,000 mi.105,667 mi.60,000 mi.164,000 mi.166,549 mi.72,000 mi.10,300 mi.123,500 mi.18,000 mi.61,720 mi.53,000 mi.24,059 mi.118,500 mi.6,640 mi.13,100 mi.41,050 mi.52,000 mi.38,900 mi.5,200 mi.120,000 mi.39,000 mi.49,279 mi.80,000 mi.143,095 mi.204,000 mi.207,571 mi.36,021 mi.240,000 mi.25,462 mi.120,000 mi.194,000 mi.162,671 mi.23,292 mi.58,816 mi.172,600 mi.75,000 mi.92,149 mi.6,200 mi.148,800 mi.7,458 mi.104,000 mi.7,033 mi.42,000 mi.71,536 mi.14,676 mi.171,750 mi.88,161 mi.139,000 mi.7,600 mi.104,000 mi.85,200 mi.2,058 mi.62,257 mi.169,000 mi.2,700 mi.179,200 mi.126,700 mi.7,455 mi.39,132 mi.39,517 mi.74,000 mi.84,224 mi.18,860 mi.87,500 mi.37,806 mi.26,000 mi.60,345 mi.71,312 mi.153,800 mi.7,652 mi.56,654 mi.4,200 mi.25,548 mi.148,000 mi.86,170 mi.102,604 mi.8,660 mi.2,010 mi.130,000 mi.99,941 mi.13,465 mi.64,500 mi.52,000 mi.41,500 mi.19,200 mi.229,000 mi.129,000 mi.15,000 mi.4,753 mi.244,000 mi.48,000 mi.55,000 mi.140,401 mi.44,373 mi.11,806 mi.49,000 mi.55,621 mi.167,000 mi.24,000 mi.122,971 mi.215,000 mi.53,433 mi.97,500 mi.70,000 mi.162,750 mi.3,053 mi.20,909 mi.7,666 mi.96,653 mi.5,006 mi.145,000 mi.135,603 mi.55,900 mi.139,000 mi.30,455 mi.133,510 mi.111,228 mi.32,117 mi.2,894 mi.77,500 mi.20,497 mi.110,000 mi.162,731 mi.152,000 mi.23,133 mi.43,705 mi.26,177 mi.42,780 mi.89,000 mi.48,641 mi.111,095 mi.50,648 mi.98,000 mi.9,000 mi.74,000 mi.85,760 mi.62,000 mi.65,000 mi.24,915 mi.84,421 mi.170,000 mi.139,000 mi.4,048 mi.500 mi.20,800 mi.21,400 mi.155,000 mi.13,700 mi.20,200 mi.56,000 mi.7,900 mi.88,750 mi.5,400 mi.140,500 mi.9,111 mi.51,338 mi.110,000 mi.21,000 mi.196,300 mi.56,247 mi.11,089 mi.5,194 mi.152,195 mi.56,675 mi.59,528 mi.51,890 mi.51,855 mi.64,776 mi.161,000 mi.10,400 mi.139,804 mi.19,200 mi.11,025 mi.37,622 mi.144,000 mi.27,000 mi.1,100 mi.3,715 mi.54,000 mi.1,400 mi.35,515 mi.110,000 mi.60,000 mi.134,000 mi.36,555 mi.28,514 mi.97,579 mi.51,133 mi.50,850 mi.58,800 mi.107,800 mi.12,300 mi.9,000 mi.139,116 mi.7,000 mi.104,733 mi.68,455 mi.102,200 mi.133,598 mi.13,900 mi.169,500 mi.81,000 mi.3,158 mi.48,879 mi.167,500 mi.170,000 mi.28,150 mi.92,728 mi.194,000 mi.49,688 mi.82,963 mi.8,949 mi.29,586 mi.3,273 mi.63,866 mi.159,000 mi.135,484 mi.74,000 mi.123,500 mi.130,000 mi.8,974 mi.76,000 mi.98,888 mi.73,846 mi.4,000 mi.36,700 mi.217,500 mi.49,600 mi.202 mi.68,000 mi.31,000 mi.18,000 mi.93,000 mi.19,200 mi.141,195 mi.10,000 mi.49,000 mi.33,400 mi.111,000 mi.40,929 mi.6,700 mi.12,000 mi.2,950 mi.100,000 mi.75,151 mi.44,168 mi.51,351 mi.117,000 mi.177,000 mi.11,597 mi.13,500 mi.16,000 mi.122,770 mi.22,000 mi.170,443 mi.75,466 mi.56,000 mi.42,479 mi.195,361 mi.185,000 mi.7,624 mi.137,000 mi.97,000 mi.122,961 mi.75,000 mi.76,500 mi.12,500 mi.128,000 mi.6,000 mi.20,200 mi.40,011 mi.2,550 mi.75,124 mi.66,840 mi.1,800 mi.17,300 mi.87,000 mi.92,530 mi.75,000 mi.93,009 mi.24,670 mi.12,600 mi.15,500 mi.2,300 mi.37,161 mi.44,800 mi.24,965 mi.97,146 mi.21,478 mi.63,000 mi.163,500 mi.119,000 mi.45,000 mi.100,574 mi.134,602 mi.86,000 mi.100,600 mi.53,000 mi.74,582 mi.115,872 mi.24,847 mi.43,000 mi.87,500 mi.67,303 mi.116,320 mi.22,200 mi.73,500 mi.95,271 mi.121,500 mi.170,000 mi.61,494 mi.111,000 mi.44,000 mi.23,152 mi.87,305 mi.85,000 mi.76,857 mi.42,626 mi.10,800 mi.20,386 mi.61,074 mi.40,208 mi.300,183 mi.49,000 mi.189,719 mi.188,000 mi.135,000 mi.33,000 mi.73,350 mi.114,000 mi.145,565 mi.62,197 mi.36,500 mi.64,000 mi.36,000 mi.218,000 mi.256,000 mi.8,228 mi.188,000 mi.7,751 mi.78,000 mi.73,000 mi.66,000 mi.70,000 mi.7,928 mi.12,700 mi.75,800 mi.171,079 mi.153,250 mi.138,450 mi.98,231 mi.201,509 mi.179,000 mi.92,861 mi.232,492 mi.29,475 mi.43,000 mi.131,100 mi.34,845 mi.55,000 mi.1,389 mi.33,700 mi.29,500 mi.70,000 mi.124,705 mi.73,000 mi.2,620 mi.14,976 mi.78,000 mi.141,209 mi.148,000 mi.150,000 mi.63,250 mi.1,800 mi.14,684 mi.43,000 mi.134,000 mi.96,000 mi.133,255 mi.31,917 mi.172,024 mi.17,000 mi.106,500 mi.24,778 mi.100,100 mi.2,750 mi.251,634 mi.54,320 mi.102,681 mi.40,000 mi.91,300 mi.19,000 mi.39,960 mi.97,724 mi.15,592 mi.54,000 mi.1,240 mi.5,000 mi.151,544 mi.90,305 mi.141,800 mi.143,000 mi.285,000 mi.95,000 mi.122,000 mi.37,700 mi.48,500 mi.33,812 mi.45,000 mi.85,458 mi.47,800 mi.13,900 mi.19,987 mi.17,761 mi.1,575 mi.14,770 mi.9,005 mi.3,000 mi.31,000 mi.8,870 mi.20,000 mi.38,686 mi.2,250 mi.33,080 mi.71,200 mi.66,500 mi.108,045 mi.192,100 mi.195,500 mi.65,441 mi.30,918 mi.60,260 mi.28,105 mi.18,000 mi.187,000 mi.23,850 mi.32,437 mi.568 mi.232,000 mi.118,000 mi.42,728 mi.16,700 mi.53,000 mi.48,054 mi.160,000 mi.28,260 mi.68,749 mi.239,000 mi.12,500 mi.53,000 mi.29,816 mi.71,000 mi.31,000 mi.40,110 mi.16,100 mi.10,400 mi.32,268 mi.107,500 mi.60,109 mi.38,600 mi.58,500 mi.35,921 mi.3,763 mi.1,800 mi.38,514 mi.15,555 mi.89,000 mi.87,501 mi.53,401 mi.80,800 mi.67,072 mi.25,000 mi.85,000 mi.82,900 mi.123,921 mi.64,000 mi.144,200 mi.190,321 mi.57,000 mi.33,000 mi.23,300 mi.31,000 mi.244,000 mi.10,500 mi.31,250 mi.45,979 mi.59,678 mi.133,300 mi.153,818 mi.149,000 mi.112,000 mi.127,558 mi.30,301 mi.26,540 mi.19,900 mi.12,000 mi.40,570 mi.36,294 mi.13,232 mi.11,500 mi.72,393 mi.105,674 mi.117,000 mi.36,000 mi.101,387 mi.59,459 mi.94,650 mi.94,300 mi.22,169 mi.36,821 mi.34,000 mi.33,818 mi.64,517 mi.68,000 mi.161,000 mi.113,294 mi.134,000 mi.69,000 mi.8,237 mi.163,500 mi.106,000 mi.162,000 mi.17,000 mi.72,128 mi.19,200 mi.9,142 mi.45,000 mi.17,451 mi.128,000 mi.102,000 mi.163,000 mi.60,660 mi.122,650 mi.29,719 mi.32,957 mi.17,500 mi.13,856 mi.7,661 mi.4,500 mi.51,902 mi.140,450 mi.41,650 mi.2,800 mi.195,000 mi.111,700 mi.18,000 mi.1,889 mi.31,600 mi.248,000 mi.91,000 mi.64,552 mi.64,957 mi.92,800 mi.14,361 mi.235,000 mi.315,000 mi.53,500 mi.94,634 mi.18,465 mi.74,500 mi.1,295 mi.158,000 mi.92,000 mi.79,615 mi.92,421 mi.110,000 mi.35,500 mi.207,100 mi.81,000 mi.182,000 mi.20,678 mi.85,000 mi.39,105 mi.115,402 mi.59,500 mi.80,134 mi.9,500 mi.69,205 mi.7,346 mi.158,366 mi.156,856 mi.271,000 mi.114,323 mi.33,000 mi.112,000 mi.35,900 mi.71,924 mi.112,180 mi.42,609 mi.44,460 mi.33,705 mi.27,407 mi.45,163 mi.80,200 mi.38,560 mi.69,849 mi.110,000 mi.228,000 mi.66,281 mi.16,850 mi.39,000 mi.22,000 mi.82,146 mi.92,000 mi.176,691 mi.124,000 mi.54,000 mi.333,361 mi.97,700 mi.43,329 mi.28,220 mi.18,533 mi.26,000 mi.30,176 mi.5,500 mi.9,281 mi.112,000 mi.126,225 mi.95,500 mi.94,000 mi.157,500 mi.138,415 mi.160,000 mi.52,675 mi.137,000 mi.53,782 mi.17,300 mi.64,500 mi.223,824 mi.64,532 mi.28,000 mi.17,000 mi.6,600 mi.28,724 mi.36,000 mi.16,478 mi.52,500 mi.120,000 mi.470 mi.86,000 mi.88,883 mi.19,590 mi.75,200 mi.17,000 mi.26,840 mi.110,450 mi.77,107 mi.49,170 mi.17,836 mi.16,400 mi.24,207 mi.79,635 mi.33,700 mi.67,650 mi.42,000 mi.169,802 mi.27,300 mi.152,000 mi.205,000 mi.85,500 mi.16,500 mi.18,515 mi.115,000 mi.81,778 mi.150,000 mi.169,613 mi.69,800 mi.64,309 mi.245,000 mi.8,000 mi.42,245 mi.48,619 mi.1,500 mi.25,880 mi.19,400 mi.162,000 mi.156,453 mi.50,780 mi.9,990 mi.104,000 mi.13,865 mi.133,504 mi.73,049 mi.92,671 mi.20,800 mi.36,500 mi.93,400 mi.45,578 mi.9,095 mi.16,000 mi.52,000 mi.149,000 mi.25,352 mi.132,269 mi.56,946 mi.37,100 mi.51,000 mi.186,268 mi.67,015 mi.44,000 mi.169,000 mi.66,770 mi.67,550 mi.3,400 mi.3,596 mi.35,597 mi.5,800 mi.130,200 mi.119,000 mi.23,842 mi.923 mi.84,352 mi.15,600 mi.2,489 mi.45,000 mi.14,900 mi.89,988 mi.92,000 mi.4,200 mi.48,500 mi.90,067 mi.61,001 mi.121,630 mi.29,830 mi.18,500 mi.17,850 mi.170,000 mi.85,253 mi.15,198 mi.67,500 mi.72,000 mi.52,000 mi.163,000 mi.62,500 mi.31,654 mi.101,000 mi.54,357 mi.132,000 mi.107,000 mi.85,149 mi.2,000 mi.51,300 mi.84,351 mi.31,729 mi.67,482 mi.24,000 mi.51,808 mi.22,985 mi.48,549 mi.6,400 mi.26,465 mi.37,594 mi.195 mi.52,246 mi.58,700 mi.6,200 mi.105,500 mi.49,700 mi.25,717 mi.166,200 mi.32,000 mi.1,897 mi.75,600 mi.208 mi.57,912 mi.26,500 mi.25,240 mi.95,000 mi.34,672 mi.115,000 mi.89,352 mi.129,000 mi.119,000 mi.162,100 mi.194,454 mi.105,000 mi.82,000 mi.12,000 mi.37,060 mi.87,248 mi.83,000 mi.2,823 mi.152,000 mi.63,900 mi.126,000 mi.87,500 mi.76,163 mi.15,629 mi.13,700 mi.143,000 mi.74,349 mi.85,000 mi.2,050 mi.149,460 mi.48,000 mi.81,000 mi.6,217 mi.8,911 mi.20,000 mi.161,933 mi.98,995 mi.67,516 mi.109,357 mi.98,000 mi.148,949 mi.3,000 mi.147,191 mi.97,496 mi.77,699 mi.23,400 mi.18,083 mi.49,105 mi.194,500 mi.43,433 mi.60,807 mi.74,864 mi.76,296 mi.115,000 mi.30,426 mi.93,000 mi.94,500 mi.95,000 mi.137,000 mi.137,500 mi.45,617 mi.36,526 mi.142,792 mi.85,000 mi.55,018 mi.92,031 mi.9,978 mi.117,000 mi.85,500 mi.119,000 mi.8,210 mi.142,400 mi.96,000 mi.116,210 mi.222,600 mi.53,850 mi.92,800 mi.86,000 mi.63,460 mi.28,500 mi.16,500 mi.7,500 mi.47,589 mi.31,681 mi.51,300 mi.96,343 mi.115,282 mi.30,900 mi.183,544 mi.230,000 mi.110,000 mi.99,500 mi.73,091 mi.9,980 mi.16,919 mi.26,339 mi.116,226 mi.120,000 mi.27,352 mi.58,000 mi.940 mi.83,858 mi.144,000 mi.11,250 mi.44,691 mi.187,000 mi.124,000 mi.96,000 mi.26,000 mi.65,212 mi.88,450 mi.2,043 mi.76,000 mi.26,470 mi.24,900 mi.100,080 mi.300,000 mi.32,652 mi.107,750 mi.100 mi.22,600 mi.47,907 mi.12,941 mi.81,500 mi.100,795 mi.48,306 mi.52,673 mi.30,022 mi.112,552 mi.2,500 mi.58,000 mi.145,000 mi.167,500 mi.102,000 mi.131,800 mi.11,563 mi.4,785 mi.63,500 mi.29,720 mi.11,000 mi.9,950 mi.20,319 mi.5,400 mi.10,200 mi.57,500 mi.7,523 mi.26,000 mi.12,000 mi.12,900 mi.48,000 mi.8,730 mi.2,121 mi.23,600 mi.2,046 mi.7,396 mi.8,100 mi.64,200 mi.22,564 mi.47,245 mi.25,420 mi.11,649 mi.110,500 mi.82,000 mi.42,653 mi.42,750 mi.190,640 mi.160,265 mi.96,400 mi.156,350 mi.175,000 mi.156,111 mi.145,000 mi.14,442 mi.13,935 mi.167,300 mi.33,523 mi.119,900 mi.44,000 mi.101,000 mi.96,473 mi.82,323 mi.192,000 mi.73,549 mi.2,978 mi.82,500 mi.224,000 mi.18,385 mi.167,506 mi.23,131 mi.55,100 mi.185,000 mi.22,227 mi.111,000 mi.176,261 mi.107,000 mi.135,350 mi.184,000 mi.405,000 mi.20,229 mi.58,981 mi.121,212 mi.122,000 mi.125,000 mi.170,000 mi.26,998 mi.71,000 mi.62,000 mi.51,300 mi.28,886 mi.80,500 mi.62,200 mi.44,300 mi.91,600 mi.6,025 mi.90,742 mi.26,900 mi.72,900 mi.9,642 mi.40,069 mi.110,900 mi.137,333 mi.155,000 mi.145,000 mi.153,692 mi.101,750 mi.149,961 mi.109,000 mi.169,900 mi.201,000 mi.63,750 mi.179,400 mi.130,000 mi.89,900 mi.118,000 mi.107,481 mi.28,600 mi.72,000 mi.45,303 mi.55,000 mi.654 mi.149,000 mi.800 mi.26,895 mi.75,000 mi.60,000 mi.1,500 mi.72,000 mi.66,126 mi.116,612 mi.45,800 mi.25,000 mi.15,698 mi.153,332 mi.18,500 mi.13,666 mi.45,815 mi.69,487 mi.60,000 mi.32,697 mi.107,000 mi.55,359 mi.61,300 mi.30,565 mi.83,000 mi.49,500 mi.138,000 mi.5,100 mi.127,500 mi.65,000 mi.128,000 mi.154,000 mi.127,941 mi.3,402 mi.13,610 mi.16,200 mi.68,050 mi.13,044 mi.136,991 mi.145,000 mi.92,225 mi.96,476 mi.52,060 mi.43,903 mi.96,419 mi.135,000 mi.98,700 mi.120,250 mi.11,650 mi.143,898 mi.57,690 mi.39,913 mi.2,905 mi.22,829 mi.117,500 mi.34,742 mi.3,800 mi.165,454 mi.89,000 mi.56,837 mi.66,000 mi.82,900 mi.9,400 mi.84,129 mi.35,550 mi.33,100 mi.120,321 mi.71,669 mi.130,921 mi.49,000 mi.37,100 mi.100,564 mi.60,058 mi.37,900 mi.154,247 mi.88,977 mi.103,010 mi.51,500 mi.26,520 mi.130,000 mi.116,451 mi.158,564 mi.51,850 mi.107,380 mi.39,000 mi.33,300 mi.93,500 mi.141,775 mi.143,250 mi.127,356 mi.94,000 mi.49,872 mi.67,000 mi.69,000 mi.6,000 mi.48,000 mi.70,312 mi.38,400 mi.106,500 mi.110,000 mi.51,000 mi.49,860 mi.95,400 mi.71,000 mi.161,894 mi.63,496 mi.87,009 mi.99,000 mi.8,600 mi.89,106 mi.3,300 mi.190,120 mi.137,000 mi.23,344 mi.120,000 mi.90,000 mi.121,525 mi.71,097 mi.52,750 mi.60,000 mi.84,900 mi.79,785 mi.91,239 mi.33,500 mi.88,900 mi.38,000 mi.136,390 mi.55,000 mi.16,002 mi.134,000 mi.87,8

In [30]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,"193,783 mi.","$10,000",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,258.000000,3.2,258.0
1,2022,"16,120 mi.","$26,599",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,332.288437,2.4,2.0
2,2012,"70,000 mi.","$15,051",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,305.000000,3.7,305.0
3,2018,"32,260 mi.","$20,999",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,201.000000,2.4,201.0
4,2021,"29,000 mi.","$39,650",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,272.000000,2.0,272.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,"196,000 mi.","$6,499",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,235.000000,3.2,235.0
4004,2013,"73,000 mi.","$13,900",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,227.000000,2.5,227.0
4005,2020,"44,487 mi.","$65,000",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4006,2021,"24,158 mi.","$44,900",False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,400.000000,2.0,400.0
4007,2019,"20,623 mi.","$36,800",False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,330.000000,2.0,330.0

In [31]:
print(final_df.dtypes)

model_year                   int64
milage                      object
price                       object
brand_Alfa                    bool
brand_Aston                   bool
                            ...
fuel_type_not supported       bool
fuel_type_â€“                   bool
horsepower                 float64
engine_L                   float64
cylinders                  float64
Length: 68, dtype: object

In [33]:
final_df['price'] = final_df['price'].replace(r'[\$,]', '', regex=True).astype(float)
final_df["milage"] = final_df["milage"].str.replace(",", "").str.replace(" mi", "", regex=True).astype(float)

In [34]:
final_df = final_df.astype(int)

In [35]:
final_df

,model_year,milage,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,horsepower,engine_L,cylinders
0,2008,193783,10000,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,258,3,258
1,2022,16120,26599,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,332,2,2
2,2012,70000,15051,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,305,3,305
3,2018,32260,20999,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,201,2,201
4,2021,29000,39650,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,272,2,272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,2008,196000,6499,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,235,3,235
4004,2013,73000,13900,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,227,2,227
4005,2020,44487,65000,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,400,2,400
4006,2021,24158,44900,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,400,2,400
4007,2019,20623,36800,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,330,2,330

In [36]:
X = final_df.drop(columns=['price']) 
y = final_df['price']

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [39]:
y_pred = model.predict(X_test)

In [40]:
y_pred

array([ 2.99659986e+04,  4.13772224e+04,  9.38463205e+03,  1.05478715e+04,
        7.33546411e+04,  4.42745279e+04,  2.06252821e+04,  5.77374462e+04,
        3.52188939e+04, -3.37732119e+03,  4.52454026e+04,  7.98717916e+04,
        4.85407534e+04,  4.65458719e+04,  7.14047950e+04,  5.28116981e+04,
       -1.78971360e+04,  1.45626368e+04,  3.03642916e+05,  5.83260472e+04,
        6.20098625e+03,  5.95174710e+04,  5.46102218e+04,  5.72535679e+04,
        3.01353714e+04,  4.62627302e+04,  5.18825526e+04,  1.46712287e+04,
        5.08442693e+04,  6.99400248e+04,  1.09525114e+04,  2.26266147e+04,
        3.62455630e+04,  3.35228547e+04,  4.85402814e+04,  1.80473598e+03,
        1.06051836e+04,  4.23730660e+04,  5.33625850e+04,  9.35022611e+04,
        5.59327097e+04,  7.62102975e+04,  3.33120926e+04,  4.32118275e+04,
        7.91801073e+04,  6.58366360e+04,  3.50331533e+04,  4.64895313e+04,
        9.51883811e+04,  4.39686349e+04,  2.71077203e+04,  4.56086042e+04,
        5.59562971e+04,  1.05030495e+05,  4.30407317e+04,  5.32467924e+04,
        6.06459365e+04,  4.91846372e+04,  6.48818344e+04,  1.70847256e+04,
        3.46682620e+04,  4.18553956e+04,  9.48877961e+03,  4.07288141e+05,
       -2.92502320e+03,  4.17650925e+04,  1.83395794e+04,  5.95636820e+04,
        3.16182504e+04,  1.12003299e+04,  1.31234781e+05,  6.18852342e+04,
        1.17535983e+04,  4.50878581e+04,  4.85690625e+04, -1.86924574e+04,
        6.77523818e+04, -1.48111905e+04,  2.10468049e+04,  4.32672918e+04,
        5.85579203e+03,  9.19795598e+03,  3.65663069e+04,  6.31592582e+04,
        7.86952664e+03,  6.00937426e+04,  5.98170570e+04,  5.79845762e+04,
        4.09050919e+03,  2.11573212e+04,  2.16357048e+04,  1.92138770e+04,
        4.34292564e+04,  2.73765416e+04,  3.41007741e+04,  1.06376912e+03,
        7.36127453e+03,  2.48313046e+04,  5.88251438e+04,  1.72148099e+05,
        1.93309702e+04,  5.37792606e+04,  7.25767170e+04,  5.84714170e+04,
        3.24366528e+04,  3.16471387e+04,  4.96923431e+04,  4.08336373e+04,
        3.18667114e+04,  2.52740732e+04,  1.64310859e+04,  4.38818207e+04,
        5.39437672e+04,  4.07434736e+04,  2.55656326e+04,  5.24411320e+04,
       -4.74833876e+03,  6.43929019e+04,  4.00801520e+04,  6.24211540e+04,
        1.45652111e+04,  5.11901749e+04,  2.11694940e+04,  5.41958860e+04,
        1.15200845e+04,  7.17650575e+04,  5.10985327e+04,  5.59915870e+04,
        7.10226879e+04,  6.13664835e+04,  2.87901857e+04,  5.21053850e+04,
        5.52510303e+04,  3.65580077e+04,  5.02562625e+04,  5.88816742e+04,
        2.35163215e+04,  1.39632500e+05,  6.24915611e+03,  7.42528636e+04,
        5.69487164e+04,  2.98374191e+04,  5.79795022e+04,  7.39421543e+04,
        4.87674808e+04,  6.82054511e+04,  5.88774063e+04, -2.44271129e+04,
       -2.08079327e+03,  4.22271931e+04,  3.06169695e+04,  3.91249858e+04,
        4.28674442e+04,  3.06957063e+05,  1.52939094e+04,  2.83432731e+04,
        3.46469640e+04, -1.42826746e+03,  1.19132010e+05,  4.92058832e+04,
        5.32816163e+04,  3.88684356e+05, -6.46700383e+03,  3.15663264e+04,
        2.99055687e+04,  5.61583696e+04,  2.81321441e+04,  4.83947827e+04,
        6.57964731e+04,  1.18436405e+04,  1.80794786e+04,  7.41172503e+04,
        5.21710987e+04,  2.72055829e+04,  6.10037589e+04,  5.82673445e+04,
        9.03725273e+04,  5.53166585e+04, -2.67778947e+03,  3.56025707e+04,
        5.23897083e+04,  1.29620252e+04,  2.90072449e+04,  6.92946347e+04,
        1.99133330e+04,  7.44978509e+04,  5.31453053e+04,  3.34713472e+04,
        1.58140956e+04,  6.23337842e+04,  3.63144676e+04,  4.90262692e+04,
        9.31093986e+04,  7.00918508e+03,  7.37818105e+04,  1.74193120e+04,
        4.57922468e+04,  4.90195536e+04,  3.16829340e+04, -1.09397779e+04,
        4.11506196e+04,  4.58456684e+02,  6.09479122e+04,  1.04249334e+04,
        5.42972199e+04,  6.75917043e+04,  3.46628464e+04,  4.04916991e+04,
        6.60725181e+04,  6.40700670e+04,  4.01111942e+04,  1.76058671e+04,
        1.50179930e+05,  6.62096649e+04, -3.19494173e+03,  3.76297136e+04,
        4.24215288e+04,  6.66282047e+04,  2.49822664e+04,  3.55925952e+04,
        6.74125747e+04,  3.44253082e+04,  3.15929358e+04,  6.63465731e+04,
        2.31821248e+04,  5.82613971e+03,  6.97717840e+04,  3.45129805e+04,
        1.00262792e+04,  6.76108838e+04,  1.99494056e+04,  5.89871845e+04,
        6.66795048e+04, -3.99242781e+03,  2.80973082e+04,  7.24378944e+04,
        2.09527390e+04,  2.77726770e+04,  5.84543347e+04,  5.72529864e+04,
        4.54458556e+04,  4.00492485e+04,  4.01103674e+04,  4.85089738e+04,
        1.61958633e+05,  4.98370716e+04,  4.62431953e+04,  2.63600348e+04,
        5.69279211e+04,  4.12158045e+04,  3.70964026e+04,  3.01740728e+04,
        2.38708957e+04,  4.47941974e+04, -7.20240732e+03,  2.73735832e+04,
       -1.20778277e+03,  5.38634564e+04,  3.69914651e+04,  9.79322635e+02,
        1.40344499e+04,  4.34108304e+03,  2.86584026e+04,  2.81970695e+04,
        1.62730630e+04,  1.10451003e+04,  1.23141888e+04,  2.97652903e+04,
        2.42663547e+04,  4.74182078e+04,  5.29792845e+04,  5.28353691e+04,
        1.30500585e+03,  6.81770729e+04,  1.69229216e+04,  1.45503341e+04,
        3.50326634e+04,  1.76819865e+03,  4.14367772e+04,  5.54386253e+04,
        7.28414757e+04,  4.07921074e+04,  3.98888331e+04,  3.59333150e+03,
       -2.35876626e+04, -3.29798443e+03, -3.17574920e+03,  2.32081157e+04,
        5.60690047e+04,  1.07559608e+05,  4.31952866e+04,  8.04685881e+04,
        7.97901999e+03,  1.12977502e+04,  4.77933262e+04,  9.54827650e+03,
        3.87868721e+04,  6.16669350e+04,  4.02940603e+04,  4.66366629e+03,
        4.82356254e+04,  3.85522094e+04,  5.44955982e+04,  5.19621265e+04,
        1.31181212e+04,  5.21536528e+04,  7.97752983e+04,  1.04730532e+05,
        4.31766922e+04,  4.76803589e+04,  7.52727567e+04,  6.80654625e+04,
        2.62712718e+03,  7.01373256e+04,  2.69677357e+04,  6.78344855e+04,
        4.30897565e+04,  1.84822535e+04,  2.24400354e+04,  5.89865486e+04,
        2.59103550e+04,  4.07805665e+04,  5.33268453e+04,  3.25903919e+04,
       -1.78767194e+04,  6.08946903e+04,  7.96875558e+04,  3.04630929e+04,
        2.48976913e+05,  1.09118625e+04,  7.47620891e+03, -8.03087801e+03,
        1.16743911e+04,  4.00797535e+04,  2.43527904e+04,  7.34903661e+04,
        2.88058823e+04,  2.30585947e+04,  5.71783542e+04,  6.47268386e+03,
        3.80873859e+04,  1.45038534e+04,  5.32338208e+04,  3.93557616e+04,
        2.77635476e+04,  4.43499656e+04,  5.59072958e+04,  1.69706286e+04,
        5.73398580e+04,  5.63556580e+04,  6.01869979e+04,  8.31018518e+04,
        6.55023123e+03,  9.72062949e+04,  6.26069086e+04,  5.82958913e+03,
        1.32634731e+04,  8.07048210e+03,  1.71693777e+05,  2.06554138e+04,
        4.65430933e+04,  6.76047392e+03,  4.84703544e+04,  1.17593659e+04,
        7.49275523e+04, -6.38762949e+03,  7.19178915e+04,  1.47760317e+04,
        1.24470415e+04,  8.72487294e+04,  8.12829972e+03,  4.14037463e+04,
        3.63493217e+04,  7.71531534e+04,  1.08876946e+05,  4.70709180e+04,
        7.29595852e+04,  3.25679249e+04,  4.74331053e+03,  4.40434539e+04,
        2.32990080e+04,  3.32160810e+04,  4.46981604e+04,  3.95882011e+04,
        5.51723934e+04, -1.22520832e+04,  3.10891345e+04,  1.60488214e+04,
        2.62705167e+04,  5.27190097e+04,  4.07798175e+04,  5.57388880e+04,
        2.91481807e+04,  1.83560939e+04,  4.46864478e+04,  4.22508966e+04,
        5.93651760e+04,  2.39224437e+04,  2.83050497e+04,  1.47617175e+04,
        2.39920932e+04,  5.30515975e+04,  5.63364179e+04,  5.92378821e+04,
        3.60401939e+04,  3.15936610e+04,  3.21933981e+04,  7.59458749e+04,
        4.79180654e+04,  4.29603275e+04,  4.41904737e+04,  3.58853687e+04,
        5.27231729e+04,  4.82999028e+04,  1.64475823e+04,  8.28166334e+04,
        7.66139829e+04,  4.18977157e+04,  1.72264319e+04,  8.03710310e+04,
        4.39471884e+04,  4.28668842e+04,  2.51867511e+05,  9.56998368e+04,
        3.12809304e+04,  4.29525366e+04,  2.93065521e+04,  4.90955342e+04,
        3.71215705e+04,  1.73814478e+04,  1.75518210e+03, -7.02290274e+02,
        7.93306255e+03,  7.50632187e+04,  5.89330536e+04,  1.84644193e+04,
       -1.77716966e+03,  4.46671351e+04,  3.00345971e+04,  4.58074405e+04,
        6.50168836e+04,  4.77907408e+04,  4.82754937e+04,  2.50952491e+04,
        3.75833655e+04,  6.19276403e+04,  4.69651668e+04, -1.09022015e+03,
        5.98349769e+04,  3.09934903e+04,  2.05225009e+04,  2.75993652e+04,
        1.00267007e+04,  3.65990782e+04, -4.35307152e+03,  6.92292452e+03,
        2.20495760e+04,  4.84923320e+04,  6.04757929e+04,  1.88033479e+04,
        2.24502576e+04,  5.42056540e+04,  9.61716546e+04,  3.62170737e+04,
        7.88562134e+04,  5.92643421e+04,  5.24721358e+04,  6.99438607e+04,
        1.03618161e+03,  4.62965160e+04,  2.21443391e+04,  7.78091975e+04,
        2.45260393e+04,  4.31594921e+04,  2.50896046e+04,  2.91668239e+04,
        1.20736644e+03,  3.22901975e+03,  4.54973338e+04,  6.07749890e+04,
       -5.72780405e+03,  5.41859571e+04,  4.02488492e+04,  5.38595205e+04,
        6.57771470e+04,  3.14196271e+04,  1.14109424e+04,  1.88555266e+03,
        6.49145474e+04,  3.18878746e+04,  1.17406795e+04,  7.85952937e+03,
        9.54348810e+04,  2.80558892e+03,  6.83105030e+04,  7.73289877e+04,
        2.12116643e+04,  1.13117344e+05,  1.19669528e+04,  3.23670198e+04,
        2.01156727e+04,  9.48815077e+04,  3.20747435e+04,  3.57842322e+04,
        7.25437739e+04,  6.29568930e+04,  4.21005262e+04,  6.30515770e+04,
       -1.24313892e+04,  1.77677860e+04,  5.46525318e+04,  1.11723165e+04,
        1.83496153e+02,  5.58292923e+04,  8.37056040e+04,  9.09601266e+04,
        2.25735892e+04,  2.29782273e+04,  4.65536958e+04,  2.06432496e+04,
        1.05552441e+05,  2.47255580e+04,  5.38437920e+04,  4.47998344e+04,
        6.06230616e+04,  5.90647998e+04,  2.50770750e+04,  1.50469321e+04,
        5.32372208e+04,  3.89051080e+04,  3.71185934e+04,  1.06407828e+04,
        2.50529165e+04,  3.43938004e+04,  3.69764995e+04,  7.20497646e+04,
        6.38662395e+04,  1.29758796e+05,  3.93700520e+04,  8.01866512e+04,
        4.49660937e+04,  1.01717828e+04,  5.68263914e+03,  2.23053100e+04,
        3.96415069e+04,  4.38453451e+04,  5.38044327e+04,  6.29279323e+04,
        2.89896419e+04,  5.50831945e+04, -1.22986430e+04,  2.49893801e+04,
        2.16844977e+04,  2.10257738e+04, -1.11446745e+04,  8.71816716e+03,
        1.70876982e+05,  3.82769232e+04,  5.96244780e+04,  7.03955309e+04,
        5.87287966e+04,  8.57738597e+04,  6.65090155e+04,  6.03826315e+03,
        4.16889244e+04,  1.01345858e+04,  3.22960586e+04,  6.13249589e+04,
        3.66467469e+04,  9.17068519e+04,  1.00618070e+05,  5.66620744e+04,
       -4.11653735e+03,  3.24291126e+05, -7.18812337e+02,  5.29173362e+04,
        7.30467078e+03,  2.40306048e+05,  6.64780875e+04,  7.35087461e+04,
        1.76092823e+04,  8.45688103e+04,  2.54134829e+04,  7.09422644e+04,
        2.85686366e+04,  5.96927940e+03,  7.24680755e+04,  9.01909262e+04,
        1.59978780e+04, -5.41989360e+03,  8.78421177e+04,  4.44693579e+03,
        1.01934191e+05,  5.03584941e+04,  6.90295087e+04,  7.51402192e+03,
        1.30440381e+05,  4.28049903e+04,  6.45668831e+04,  4.90523166e+04,
        8.12730947e+04,  2.92652573e+05,  8.79152722e+04,  1.32871172e+04,
        4.89191776e+04,  1.59854972e+04,  6.25281732e+04,  5.30320961e+04,
        5.86368194e+04,  3.28679940e+04,  2.76350704e+04,  4.84149631e+04,
        3.53681232e+04,  5.14451069e+04,  6.44805158e+04,  5.30880620e+03,
        5.32057209e+04,  2.50071492e+04,  1.50760998e+04,  5.82862591e+04,
        2.78303351e+04,  2.17298023e+04,  5.57265008e+04,  7.51572640e+04,
        6.87606113e+04,  9.37275573e+04,  6.18135119e+04,  2.73694173e+04,
        4.87874035e+04,  3.57631768e+04, -5.83906126e+03,  3.95834741e+04,
        3.48926412e+04,  6.92563214e+04,  8.88780072e+04,  3.12098793e+04,
        3.11693592e+04,  3.21819451e+04,  8.54868735e+02,  5.56204366e+04,
        1.09608504e+04,  9.09789027e+04,  4.33748224e+04,  1.45428915e+04,
        6.44369690e+04,  1.61295381e+04,  7.35575504e+04,  3.72948601e+04,
        2.54924260e+04,  6.42152563e+03, -2.07542586e+04,  3.79319266e+04,
        3.07779509e+04,  2.42253476e+04,  5.13888268e+04,  5.12954045e+04,
        3.15386344e+04,  6.19894702e+04,  1.10616303e+04, -1.67287127e+04,
        5.25448593e+04,  6.27851555e+03,  5.72364564e+04,  2.62421300e+04,
        4.50210453e+04,  9.05034860e+04,  5.83962704e+03,  8.13046246e+04,
        4.96247362e+04,  4.02937182e+04,  4.84289185e+04,  3.78822374e+04,
        1.28198734e+04,  7.23208321e+04,  7.96378201e+03,  3.44276313e+04,
        1.47879202e+04,  3.52853447e+04,  5.78708026e+04,  3.36851259e+04,
        4.85414776e+04,  3.95399609e+03,  3.75881737e+04,  7.92329193e+04,
        4.88396747e+04,  2.92655669e+05,  7.55438183e+02,  8.21999425e+04,
        5.88487586e+04,  4.84508346e+03,  4.99316333e+04, -3.46694389e+03,
        2.79775920e+04,  2.70844751e+04,  1.48862469e+05,  1.00024709e+05,
        4.70305468e+04,  3.57755820e+04,  7.24776011e+04,  1.10687290e+04,
        5.77068290e+04,  4.73318146e+04,  4.61347396e+04,  5.35868409e+03,
        4.86528988e+04,  2.85656335e+04, -1.14749743e+04,  4.67632604e+04,
        8.44526464e+04,  1.79239947e+04,  5.89867045e+04,  3.20096028e+04,
        5.54225077e+04,  2.19083510e+04,  5.48089562e+04,  1.32700513e+04,
        2.53231446e+03,  1.59543754e+05,  2.52294008e+04,  3.40999038e+04,
        4.46934543e+04,  2.16550365e+04,  3.53861600e+04,  6.38559223e+04,
        6.51596625e+04,  2.47222494e+04,  6.62531828e+04,  3.75113482e+04,
        4.60187999e+04,  1.93466430e+04,  2.28043938e+04,  3.19553596e+04,
        5.45157107e+04,  5.06218529e+04,  3.16495445e+04,  8.86121798e+04,
        5.29900865e+04,  5.73228098e+04,  9.99995087e+04,  4.67833881e+04,
        7.41872225e+04,  2.43192987e+04,  1.19457972e+04,  2.73202713e+04,
        1.06772290e+04, -2.65202570e+04,  5.70978120e+04,  5.86214352e+04,
        3.47994580e+04,  3.07233619e+04,  4.69722390e+04,  2.30296086e+04,
        3.06268998e+05,  7.63786340e+04,  2.11150381e+04,  6.93007344e+04,
        3.01188749e+04,  4.25554122e+04,  7.25683954e+04, -1.04444963e+04,
        1.36580358e+04,  3.14368734e+04,  4.95116002e+04, -4.09743682e+02,
       -4.24580584e+01,  1.98625719e+04,  3.80895811e+04,  5.31712279e+04,
        3.29794927e+04,  1.40369992e+04,  5.02033701e+04,  7.49963204e+04,
        3.65100078e+04, -4.34134801e+03,  7.04359938e+04,  1.11780446e+05,
        3.75091891e+04,  4.90344282e+04,  2.00430708e+04,  3.22481137e+04,
        8.33647406e+03,  6.05878693e+04,  8.37387232e+04,  3.68046354e+04,
        4.81963620e+04,  3.63598537e+04,  4.95286090e+04,  5.69098071e+04,
        3.85623008e+05,  1.73190418e+04,  5.21785522e+04,  6.93893785e+04,
        3.48116123e+03,  1.39359494e+05,  9.57866790e+04,  2.79638759e+04,
        1.74664852e+04,  4.76454300e+04, -7.76212557e+03,  2.50490931e+04,
        6.85327609e+04,  6.57283590e+04])

In [41]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"ðŸ“Š Model Evaluation:")
print(f"MAE  (Mean Absolute Error)  : {mae:.2f}")
print(f"MSE  (Mean Squared Error)   : {mse:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"RÂ² Score                    : {r2:.4f}")

ðŸ“Š Model Evaluation:
MAE  (Mean Absolute Error)  : 16887.07
MSE  (Mean Squared Error)   : 1114965112.07
RMSE (Root Mean Squared Error): 33391.09
RÂ² Score                    : 0.5109

In [42]:
coefficients = pd.DataFrame({'Feature': X.columns, 'Coefficient': model.coef_})
coefficients.sort_values(by='Coefficient', ascending=False, inplace=True)
print(coefficients)

                    Feature   Coefficient
7             brand_Bugatti  1.864995e+06
47        brand_Rolls-Royce  3.285113e+05
26        brand_Lamborghini  2.334957e+05
14            brand_Ferrari  1.937390e+05
36            brand_McLaren  1.509489e+05
..                      ...           ...
21           brand_INFINITI -7.284134e+03
22             brand_Jaguar -8.439302e+03
11           brand_Chrysler -1.050098e+04
45                brand_RAM -1.402293e+04
62  fuel_type_not supported -1.564213e+04

[67 rows x 2 columns]

In [43]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)
y_pred_poly = model_poly.predict(X_test_poly)

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"ðŸ“Š Model Evaluation:")
print(f"MAE  (Mean Absolute Error)  : {mae:.2f}")
print(f"MSE  (Mean Squared Error)   : {mse:.2f}")
print(f"RMSE (Root Mean Squared Error): {rmse:.2f}")
print(f"RÂ² Score                    : {r2:.4f}")

ðŸ“Š Model Evaluation:
MAE  (Mean Absolute Error)  : 16887.07
MSE  (Mean Squared Error)   : 1114965112.07
RMSE (Root Mean Squared Error): 33391.09
RÂ² Score                    : 0.5109

In [45]:
import numpy as np
final_df['price'] = np.log1p(final_df['price'])  # log1p avoids log(0) issues

In [46]:
final_df['car_age'] = 2025 - final_df['model_year']  
final_df.drop(columns=['model_year'], inplace=True)

In [47]:
final_df['mileage_per_year'] = final_df['milage'] / final_df['car_age']
final_df['mileage_per_year'] = final_df['mileage_per_year'].fillna(final_df['milage'])

In [48]:
final_df['hp_per_liter'] = final_df['horsepower'] / final_df['engine_L']
final_df['hp_per_liter'] = final_df['hp_per_liter'].fillna(final_df['horsepower'])

In [49]:
final_df.drop(columns=['horsepower','milage'],inplace=True)

In [50]:
final_df

,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,...,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,engine_L,cylinders,car_age,mileage_per_year,hp_per_liter
0,9.210440,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,258,17,11399.000000,86.000000
1,10.188666,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,2,3,5373.333333,166.000000
2,9.619266,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,305,13,5384.615385,101.666667
3,9.952278,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,201,7,4608.571429,100.500000
4,10.587871,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,272,4,7250.000000,136.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,8.779557,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,235,17,11529.411765,78.333333
4004,9.539716,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,227,12,6083.333333,113.500000
4005,11.082158,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,5,8897.400000,200.000000
4006,10.712215,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,4,6039.500000,200.000000
4007,10.513280,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,330,6,3437.166667,165.000000

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
X = final_df.drop(columns=['price'])
y = final_df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"ðŸ“Š Model Evaluation AFTER Feature Engineering:")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"RÂ² Score : {r2:.4f}")

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [52]:
print(df.describe())

        model_year
count  4008.000000
mean   2015.517465
std       6.104423
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [53]:
print(final_df.isnull().sum())
print(final_df.isin([np.inf, -np.inf]).sum())

price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64
price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        5
Length: 68, dtype: int64

In [54]:
final_df.replace([np.inf, -np.inf], np.nan, inplace=True)  
final_df.fillna(final_df.mean(), inplace=True)

In [55]:
final_df

,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,brand_Chevrolet,...,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_â€“,engine_L,cylinders,car_age,mileage_per_year,hp_per_liter
0,9.210440,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,258,17,11399.000000,86.000000
1,10.188666,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,2,3,5373.333333,166.000000
2,9.619266,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,305,13,5384.615385,101.666667
3,9.952278,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,201,7,4608.571429,100.500000
4,10.587871,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,272,4,7250.000000,136.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,8.779557,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,3,235,17,11529.411765,78.333333
4004,9.539716,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,227,12,6083.333333,113.500000
4005,11.082158,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,5,8897.400000,200.000000
4006,10.712215,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,400,4,6039.500000,200.000000
4007,10.513280,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,2,330,6,3437.166667,165.000000

In [56]:
print(final_df.isnull().sum())
print(final_df.isin([np.inf, -np.inf]).sum())

price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64
price               0
brand_Alfa          0
brand_Aston         0
brand_Audi          0
brand_BMW           0
                   ..
engine_L            0
cylinders           0
car_age             0
mileage_per_year    0
hp_per_liter        0
Length: 68, dtype: int64

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
X = final_df.drop(columns=['price'])
y = final_df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"ðŸ“Š Model Evaluation AFTER Feature Engineering:")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"RÂ² Score : {r2:.4f}")

ðŸ“Š Model Evaluation AFTER Feature Engineering:
MAE  : 0.29
MSE  : 0.15
RMSE : 0.39
RÂ² Score : 0.7870

In [58]:
y_pred = model.predict(X_test) 
results = pd.DataFrame({'Actual Price': y_test, 'Predicted Price': y_pred})
print(results.head())

      Actual Price  Predicted Price
2580      9.609184         9.415637
3659     10.373522        10.524507
897       9.680406         9.812410
2091      9.433564         9.192103
1044     11.361986        11.517710

In [59]:
import pickle
# Save the trained model
with open("car_price_model.pkl", "wb") as file:
    pickle.dump(model, file)
# Save the feature names (to prevent column mismatch issues later)
with open("feature_names.pkl", "wb") as file:
    pickle.dump(X_train.columns.tolist(), file)
print("âœ… Model and feature names saved successfully!")

âœ… Model and feature names saved successfully!

## UPDATED DATAFRAME WITH ONLY ESSENTIAL COLUMNS

In [60]:
# Preprocess and Save Template in Jupyter Notebook
import pickle
import pandas as pd

# Load trained model
with open("car_price_model.pkl", "rb") as file:
    model = pickle.load(file)

# Load feature names
with open("feature_names.pkl", "rb") as file:
    feature_names = pickle.load(file)

# Create an empty DataFrame with correct columns
template_df = pd.DataFrame(columns=feature_names)
template_df.loc[0] = [0] * len(feature_names)  # Initialize with zeros

# Save this template DataFrame
with open("template_df.pkl", "wb") as file:
    pickle.dump(template_df, file)

print("âœ… Template DataFrame saved successfully!")

âœ… Template DataFrame saved successfully!

### Use Pre-Saved Template in Streamlit (app.py)

In [61]:
import pickle

# Load trained model
with open("car_price_model.pkl", "rb") as file:
    model = pickle.load(file)

# Load feature names
with open("feature_names.pkl", "rb") as file:
    feature_names = pickle.load(file)

print("âœ… Model Feature Names:", feature_names)

âœ… Model Feature Names: ['brand_Alfa', 'brand_Aston', 'brand_Audi', 'brand_BMW', 'brand_Bentley', 'brand_Bugatti', 'brand_Buick', 'brand_Cadillac', 'brand_Chevrolet', 'brand_Chrysler', 'brand_Dodge', 'brand_FIAT', 'brand_Ferrari', 'brand_Ford', 'brand_GMC', 'brand_Genesis', 'brand_Honda', 'brand_Hummer', 'brand_Hyundai', 'brand_INFINITI', 'brand_Jaguar', 'brand_Jeep', 'brand_Karma', 'brand_Kia', 'brand_Lamborghini', 'brand_Land', 'brand_Lexus', 'brand_Lincoln', 'brand_Lotus', 'brand_Lucid', 'brand_MINI', 'brand_Maserati', 'brand_Maybach', 'brand_Mazda', 'brand_McLaren', 'brand_Mercedes-Benz', 'brand_Mercury', 'brand_Mitsubishi', 'brand_Nissan', 'brand_Plymouth', 'brand_Polestar', 'brand_Pontiac', 'brand_Porsche', 'brand_RAM', 'brand_Rivian', 'brand_Rolls-Royce', 'brand_Saab', 'brand_Saturn', 'brand_Scion', 'brand_Subaru', 'brand_Suzuki', 'brand_Tesla', 'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo', 'fuel_type_Diesel', 'fuel_type_E85 Flex Fuel', 'fuel_type_Gasoline', 'fuel_type_Hybrid', 'fuel_type_Plug-In Hybrid', 'fuel_type_not supported', 'fuel_type_â€“', 'engine_L', 'cylinders', 'car_age', 'mileage_per_year', 'hp_per_liter']

#### FINAL DATASET

In [62]:
final_df.to_csv("final_dataset.csv", index=False)